import { useEffect, useState } from 'react';
import { ArrowLeft, Check, Lock, Play, Save } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import axios from 'axios';
import './sensitivity.css';
import TestProcedureInfo from '../guidance/TestProcedureInfo';

const units = ['mg', 'g', 'kg', 't'];
const format = (value: unknown, unit?: string) => Number.isFinite(Number(value)) ? `${new Intl.NumberFormat('en-IN', { maximumFractionDigits: 9 }).format(Number(value))}${unit ? ` ${unit}` : ''}` : '—';

export default function SensitivityWorkspace() {
  const { reportId = '' } = useParams(); const [data, setData] = useState<any>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { setError(''); try { const response = await axios.get(`/test-reports/${reportId}/sensitivity`); setData(response.data); } catch (e: any) { setError(e.response?.data?.message || 'Unable to load the sensitivity test.'); } };
  useEffect(() => { void load(); }, [reportId]);
  const start = async () => { setBusy(true); try { const response = await axios.post(`/test-reports/${reportId}/sensitivity/start`); setData((current: any) => ({ ...current, ...response.data })); setError(''); } catch (e: any) { setError(e.response?.data?.message || 'Unable to start the sensitivity test.'); } finally { setBusy(false); } };
  if (!data) return <main className="sensitivity-page"><div className="sensitivity-loading">{error || 'Loading sensitivity test…'}</div></main>;
  const { applicability, test } = data; const snapshot = test?.instrumentSnapshot || data.report?.instrument || {}; const unit = snapshot.unit || 'g'; const supported = applicability?.executionSupported === true && applicability?.status === 'APPLICABLE'; const stages = test?.stages || []; const activeIndex = stages.findIndex((stage: any) => stage.status !== 'COMPLETED'); const active = activeIndex >= 0 ? stages[activeIndex] : null;
  return <main className="sensitivity-page">
    <header className="sensitivity-top"><Link to={`/tester/reports/${reportId}/testing`}><ArrowLeft size={16} /> Testing route</Link><div><strong>NAWI</strong><span>TEST &amp; REPORT SYSTEM</span></div><span>OIML R 76 A.4.9</span></header>
    <section className="sensitivity-content"><header className="sensitivity-heading"><div><span className="technical-label">TESTING · A.4.9</span><h1>Sensitivity</h1><p>Minimum sensitivity of a non-self-indicating instrument.</p></div><span className={`sensitivity-status ${String(test?.result || applicability?.status || '').toLowerCase()}`}>{test?.result && test.result !== 'NOT_DETERMINED' ? test.result : test?.status || applicability?.status}</span></header>
      {error && <div className="sensitivity-error">{error}</div>}
      <section className="sensitivity-context"><div><small>Class</small><strong>{snapshot.accuracyClass || '—'}</strong></div><div><small>Min</small><strong>{format(snapshot.min, unit)}</strong></div><div><small>Max</small><strong>{format(snapshot.max, unit)}</strong></div><div><small>e</small><strong>{format(snapshot.e, unit)}</strong></div><div><small>d</small><strong>{format(snapshot.d, unit)}</strong></div><div><small>Indication</small><strong>{snapshot.indicationType || '—'}</strong></div></section>
      {!supported ? <section className="sensitivity-panel"><span className="technical-label">EXECUTION UNAVAILABLE</span><h2>{applicability?.status === 'NOT_APPLICABLE' ? 'A.4.9 is not applicable' : 'Configuration or procedure required'}</h2><p>{applicability?.reason || 'Complete the instrument configuration before starting this procedure.'}</p><Link className="sensitivity-secondary" to={`/tester/reports/${reportId}/testing`}>Back to Testing</Link></section> : !test ? <section className="sensitivity-panel sensitivity-start"><div><span className="technical-label">NON-SELF-INDICATING INSTRUMENT</span><h2>Two-load minimum-sensitivity procedure</h2><p>The required loads are derived from the persisted instrument snapshot: zero and Max. The application will calculate the required extra load from the existing MPE engine.</p></div><button className="sensitivity-primary" disabled={busy} onClick={() => void start()}><Play size={16} /> Start Test</button></section> : <>
        <section className="sensitivity-procedure"><div><span className="technical-label">PROCEDURE CONFIRMATION</span><h2>Observe the instrument physically</h2><ol><li>Ensure the instrument is oscillating normally before applying the extra load.</li><li>Apply the extra load while the load receptor is still oscillating.</li><li>{snapshot.indicationDamping === 'DAMPED' ? 'For a damped instrument, apply the extra load with a slight impact.' : 'If the instrument is damped, apply the extra load with a slight impact.'}</li><li>Determine the linear distance between the middle points of the indication before and after the extra load.</li></ol></div><ProcedureConfirmation test={test} damped={snapshot.indicationDamping === 'DAMPED'} busy={busy} onSaved={saved => setData((current: any) => ({ ...current, test: saved }))} onError={setError} /></section>
        <section className="sensitivity-progress" aria-label="Sensitivity stages">{stages.map((stage: any, index: number) => <div className={stage.status === 'COMPLETED' ? 'complete' : index === activeIndex ? 'active' : 'locked'} key={stage.stageId}><span>{stage.status === 'COMPLETED' ? <Check size={15} /> : stage.status === 'LOCKED' ? <Lock size={14} /> : index + 1}</span><strong>{stage.label}</strong><small>{format(stage.appliedTestLoad?.value, stage.appliedTestLoad?.unit || unit)}</small></div>)}</section>
        {active ? <SensitivityStageForm key={`${active.stageId}-${active.observation?.recordedAt || 'new'}`} stage={active} unit={unit} procedureConfirmed={test.procedureConfirmation?.normalOscillationConfirmed === true} busy={busy} onSubmit={async values => { setBusy(true); try { const response = await axios.patch(`/test-reports/${reportId}/sensitivity/stages/${active.stageId}`, values); setData((current: any) => ({ ...current, test: response.data.test })); setError(''); } catch (e: any) { setError(e.response?.data?.message || 'Unable to save the sensitivity observation.'); } finally { setBusy(false); } }} /> : <section className="sensitivity-panel sensitivity-complete"><Check size={24} /><h2>A.4.9 Sensitivity completed · {test.result}</h2><p>Both required load stages were evaluated from the saved physical observations.</p><Link className="sensitivity-secondary" to={`/tester/reports/${reportId}/testing`}>Return to Testing</Link></section>}
        <section className="sensitivity-panel"><div className="sensitivity-panel-title"><div><span className="technical-label">TRACEABILITY</span><h2>OIML procedure</h2></div><span>OIML R 76-1:2006 Annex A A.4.9 · §6.1</span></div><p>The MPE determines the required extra load. Acceptance is based separately on the measured permanent linear displacement and the class/capacity requirement.</p></section>
        <TestProcedureInfo testId="A.4.9" configuration={{ ...snapshot, applicabilityStatus: applicability?.status }} />
      </>}
    </section>
  </main>;
}

function ProcedureConfirmation({ test, damped, busy, onSaved, onError }: { test: any; damped: boolean; busy: boolean; onSaved: (test: any) => void; onError: (message: string) => void }) {
  const [dampedConfirmed, setDampedConfirmed] = useState(test.procedureConfirmation?.dampedProcedureConfirmed === true);
  const normalConfirmed = test.procedureConfirmation?.normalOscillationConfirmed === true;
  const save = async (nextDamped: boolean) => { if (!normalConfirmed) return; try { const response = await axios.patch(`/test-reports/${window.location.pathname.split('/')[3]}/sensitivity/procedure`, { normalOscillationConfirmed: true, dampedProcedureConfirmed: nextDamped }); onSaved(response.data.test); } catch (e: any) { onError(e.response?.data?.message || 'Unable to save procedure confirmation.'); } };
  return <div className="sensitivity-confirm"><label><input type="checkbox" checked={normalConfirmed} onChange={async event => { if (!event.target.checked) return; try { const response = await axios.patch(`/test-reports/${window.location.pathname.split('/')[3]}/sensitivity/procedure`, { normalOscillationConfirmed: true, ...(damped ? { dampedProcedureConfirmed: dampedConfirmed } : {}) }); onSaved(response.data.test); } catch (e: any) { onError(e.response?.data?.message || 'Unable to save procedure confirmation.'); } }} disabled={busy || normalConfirmed} /> I confirm the physical procedure was followed.</label>{damped && <label><input type="checkbox" checked={dampedConfirmed} onChange={event => { setDampedConfirmed(event.target.checked); if (event.target.checked) void save(true); }} disabled={busy || dampedConfirmed} /> I confirm the extra load was applied with a slight impact.</label>}<small>This confirmation records the tester’s observation; it does not prove oscillation electronically.</small></div>;
}

function SensitivityStageForm({ stage, unit, procedureConfirmed, busy, onSubmit }: { stage: any; unit: string; procedureConfirmed: boolean; busy: boolean; onSubmit: (values: any) => Promise<void> }) {
  const saved = stage.observation || {}; const [values, setValues] = useState({ actualExtraLoad: String(saved.raw?.actualExtraLoad ?? ''), actualExtraLoadUnit: saved.raw?.actualExtraLoadUnit || unit, middlePointBefore: String(saved.raw?.middlePointBefore ?? ''), middlePointAfter: String(saved.raw?.middlePointAfter ?? ''), notes: saved.notes || '' });
  const set = (key: string, value: string) => setValues(current => ({ ...current, [key]: value })); const displacement = values.middlePointBefore !== '' && values.middlePointAfter !== '' ? Math.abs(Number(values.middlePointAfter) - Number(values.middlePointBefore)) : undefined; const required = ['actualExtraLoad', 'middlePointBefore', 'middlePointAfter'].every(key => values[key as keyof typeof values] !== '');
  const submit = (complete: boolean) => void onSubmit({ actualExtraLoad: Number(values.actualExtraLoad), actualExtraLoadUnit: values.actualExtraLoadUnit, middlePointBefore: Number(values.middlePointBefore), middlePointAfter: Number(values.middlePointAfter), notes: values.notes, complete });
  return <section className="sensitivity-panel sensitivity-stage"><div className="sensitivity-panel-title"><div><span className="technical-label">ACTIVE STAGE · {stage.label}</span><h2>Applied test load {format(stage.appliedTestLoad?.value, stage.appliedTestLoad?.unit || unit)}</h2><p>Enter only the physical observations. Derived requirements and result are calculated by the server.</p></div><strong>{stage.status}</strong></div><div className="sensitivity-derived"><div><small>Applicable MPE</small><b>±{format(stage.applicableMpe?.value, stage.applicableMpe?.unit || unit)}</b></div><div><small>Absolute MPE</small><b>{format(stage.absoluteMpe?.value, stage.absoluteMpe?.unit || unit)}</b></div><div><small>Minimum extra load</small><b>{format(stage.minimumExtraLoad?.value, stage.minimumExtraLoad?.unit)}</b></div><div><small>Required extra load</small><b>{format(stage.requiredExtraLoad?.value, stage.requiredExtraLoad?.unit)}</b></div><div><small>Minimum permanent displacement</small><b>{format(stage.minimumPermanentDisplacement?.value, stage.minimumPermanentDisplacement?.unit)}</b></div></div><div className="sensitivity-instruction"><strong>Measure the middle point of the indication before and after the extra load.</strong><span>The linear displacement is measured in mm. Do not enter a mass change as a substitute.</span></div><div className="sensitivity-fields"><label>Actual extra load applied<input type="number" min="0" step="any" value={values.actualExtraLoad} onChange={event => set('actualExtraLoad', event.target.value)} /><select value={values.actualExtraLoadUnit} onChange={event => set('actualExtraLoadUnit', event.target.value)}>{units.map(option => <option key={option}>{option}</option>)}</select></label><label>Middle point before extra load (mm)<input type="number" step="any" value={values.middlePointBefore} onChange={event => set('middlePointBefore', event.target.value)} /></label><label>Middle point after extra load (mm)<input type="number" step="any" value={values.middlePointAfter} onChange={event => set('middlePointAfter', event.target.value)} /></label><div className="sensitivity-live"><small>Permanent displacement</small><strong>{format(displacement, 'mm')}</strong></div><label className="sensitivity-notes">Physical observation notes<textarea value={values.notes} onChange={event => set('notes', event.target.value)} /></label></div><div className="sensitivity-actions"><button className="sensitivity-secondary" disabled={busy || !procedureConfirmed || !required} onClick={() => submit(false)}><Save size={15} /> Save observation</button><button className="sensitivity-primary" disabled={busy || !procedureConfirmed || !required} onClick={() => submit(true)}><Check size={16} /> Complete {stage.label} test</button></div></section>;
}
