import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, Clock3, Lock, Play } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import axios from 'axios';
import './stability-of-equilibrium.css';
import './stability-docs.css';
import TestProcedureInfo from '../guidance/TestProcedureInfo';
import EvidencePanel from '../evidence/EvidencePanel';

const units = ['mg', 'g', 'kg', 't'];
const fmt = (value: unknown, unit = 'g') => value === undefined || value === null || value === '' || !Number.isFinite(Number(value)) ? '—' : `${Number(value)} ${unit}`;
const fields = ['stableEquilibriumPrinciple', 'stableEquilibriumCriterion', 'adjustableParameters', 'nonAdjustableParameters', 'parameterSecurityMethod', 'worstCaseAdjustment'] as const;
const documentationChecks = [
  ['documentationAvailable', 'Manufacturer stable-equilibrium documentation available', ['Yes', 'No']],
  ['basicPrincipleDocumented', 'Basic principle / function documented', ['Yes', 'No']],
  ['criteriaDocumented', 'Stable-equilibrium criteria documented', ['Yes', 'No']],
  ['adjustableParametersDocumented', 'Adjustable parameters documented', ['Yes', 'No', 'Not applicable']],
  ['nonAdjustableParametersDocumented', 'Non-adjustable parameters documented', ['Yes', 'No', 'Not applicable']],
  ['parameterSecurityDocumented', 'Parameter security documented', ['Yes', 'No', 'Not applicable']],
  ['worstCaseAdjustmentIdentified', 'Worst-case adjustment identified', ['Yes', 'No', 'Not applicable']],
] as const;

export default function StabilityOfEquilibriumWorkspace() {
  const { reportId = '' } = useParams(); const [data, setData] = useState<any>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [now, setNow] = useState(Date.now());
  const [docs, setDocs] = useState<Record<string, string>>({ stableEquilibriumPrinciple: '', stableEquilibriumCriterion: '', adjustableParameters: '', nonAdjustableParameters: '', parameterSecurityMethod: '', worstCaseAdjustment: '', documentationAvailable: '', basicPrincipleDocumented: '', criteriaDocumented: '', adjustableParametersDocumented: '', nonAdjustableParametersDocumented: '', parameterSecurityDocumented: '', worstCaseAdjustmentIdentified: '', manufacturerDocumentationReference: '', evidenceReference: '' });
  const [actualLoad, setActualLoad] = useState(''); const [loadUnit, setLoadUnit] = useState('g'); const [printed, setPrinted] = useState(''); const [sequence, setSequence] = useState(''); const [functionTested, setFunctionTested] = useState('PRINT'); const [disturbed, setDisturbed] = useState(false); const [immediate, setImmediate] = useState(false);
  const [repetition, setRepetition] = useState(1); const [continuous, setContinuous] = useState<Record<string, string>>({}); const [zeroTrackingOffConfirmed, setZeroTrackingOffConfirmed] = useState(false);
  const load = async () => { try { const response = await axios.get(`/test-reports/${reportId}/stability-of-equilibrium`); setData(response.data); if (response.data.test?.documentation) setDocs(response.data.test.documentation); } catch (e: any) { setError(e.response?.data?.message || 'Unable to load Stability of equilibrium.'); } };
  useEffect(() => { void load(); }, [reportId]); useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 250); return () => window.clearInterval(timer); }, []);
  const action = async (request: () => Promise<any>) => { setBusy(true); setError(''); try { const response = await request(); setData((current: any) => ({ ...current, ...response.data, test: response.data.test || current?.test })); } catch (e: any) { setError(e.response?.data?.message || 'Unable to save Stability of equilibrium.'); } finally { setBusy(false); } };
  const test = data?.test; const snapshot = test?.instrumentSnapshot || {}; const unit = snapshot.unit || 'g'; const plan = test?.plan || data?.applicability?.plan || {}; const phase = (code: string) => test?.phases?.find((item: any) => item.code === code); const phase2 = phase('A.4.12.2'); const elapsed = test?.printStorage?.commandStartedAt ? Math.max(0, (now - new Date(test.printStorage.commandStartedAt).getTime()) / 1000) : 0;
  const activeOperations = plan.applicableOperations || []; const completeDocs = fields.every(field => docs[field]?.trim()) && documentationChecks.every(([field]) => docs[field]);
  const sequenceValues = useMemo(() => sequence.split(',').map(value => Number(value.trim())).filter(value => Number.isFinite(value)), [sequence]);
  if (!data) return <main className="stability-page"><div className="stability-loading">{error || 'Loading A.4.12…'}</div></main>;
  if (!test) return <main className="stability-page"><header className="stability-top"><Link to={`/tester/reports/${reportId}/testing`}><ArrowLeft size={16} /> Testing</Link><strong>NAWI · TEST &amp; REPORT SYSTEM</strong></header><section className="stability-content"><h1>Stability of Equilibrium</h1><p>{data.applicability?.reason}</p>{error && <div className="stability-error">{error}</div>}{data.applicability?.status === 'NOT_APPLICABLE' ? <span className="stability-na-note">No test required</span> : <button className="stability-primary" disabled={busy || data.applicability?.executionSupported === false} onClick={() => void action(() => axios.post(`/test-reports/${reportId}/stability-of-equilibrium/start`))}><Play size={15} /> Start Test</button>}</section></main>;
  const saveDocs = () => action(() => axios.patch(`/test-reports/${reportId}/stability-of-equilibrium/documentation`, { ...docs }));
  const saveSetup = () => action(() => axios.patch(`/test-reports/${reportId}/stability-of-equilibrium/setup`, { actualLoad: Number(actualLoad), actualLoadUnit: loadUnit, notes: '' }));
  const startPrint = () => action(() => axios.patch(`/test-reports/${reportId}/stability-of-equilibrium/print-storage/start`, { functionTested, disturbanceConfirmed: true, initiatedImmediatelyConfirmed: true }));
  const finishPrint = () => action(() => axios.patch(`/test-reports/${reportId}/stability-of-equilibrium/print-storage/complete`, { printedValue: Number(printed), printedValueUnit: unit, observedValues: sequenceValues, observedValueUnit: unit }));
  const saveRepetition = (branch: string) => action(async () => { const response = await axios.patch(`/test-reports/${reportId}/stability-of-equilibrium/${branch === 'A.4.12.3' ? 'zero-setting' : 'tare'}/repetitions/${repetition}`, { disturbanceConfirmed: true, operationAttemptedImmediately: true, blockedBeforeStable: true, stableAfterConfirmed: true, zeroTrackingOffConfirmed, complete: true }); const saved = response.data.test; const count = (branch === 'A.4.12.3' ? saved?.zeroSetting?.repetitions : saved?.tare?.repetitions)?.length || repetition; setRepetition(Math.min(5, count + 1)); return response; });
  const saveContinuous = () => action(() => axios.patch(`/test-reports/${reportId}/stability-of-equilibrium/continuous-disturbance`, { continuousDisturbanceConfirmed: true, operations: activeOperations.map((operation: string) => ({ operation, observed: continuous[operation] || 'BLOCKED' })) }));
  const complete = () => action(() => axios.patch(`/test-reports/${reportId}/stability-of-equilibrium/complete`));
  return <main className="stability-page"><header className="stability-top"><Link to={`/tester/reports/${reportId}/testing`}><ArrowLeft size={16} /> Testing</Link><div><strong>NAWI</strong><span>TEST &amp; REPORT SYSTEM</span></div><span>{data.report?.testReportId}</span></header><section className="stability-content"><div className="stability-heading"><div><span className="stability-kicker">A.4 · PERFORMANCE TEST</span><h1>Stability of Equilibrium</h1><p>Annex A A.4.12 · stable-equilibrium behavior and function inhibition.</p></div><span className={`stability-status ${String(test.result).toLowerCase()}`}>{test.status === 'COMPLETED' ? test.result : test.status.replace(/_/g, ' ')}</span></div>{error && <div className="stability-error">{error}</div>}<section className="stability-context"><div><small>Accuracy class</small><strong>{snapshot.accuracyClass || '—'}</strong></div><div><small>Max</small><strong>{fmt(snapshot.max, unit)}</strong></div><div><small>e / d</small><strong>{fmt(snapshot.e, unit)} / {fmt(snapshot.d, unit)}</strong></div><div><small>Interval used</small><strong>{plan.stabilityInterval ? `${plan.stabilityInterval.kind} · ${fmt(plan.stabilityInterval.value, unit)}` : '—'}</strong></div><div><small>Source</small><strong>OIML R 76-1:2006</strong></div></section>
    <section className="stability-section"><span className="stability-kicker">A.4.12.1</span><h2>Stability documentation / configuration review</h2><p>Record the manufacturer’s documented principle, criteria, parameters, and parameter security. Do not invent technical values.</p><div className="stability-check-grid">{documentationChecks.map(([field, label, options]) => <label key={field}>{label}<select value={docs[field] || ''} onChange={event => setDocs({ ...docs, [field]: event.target.value })}><option value="">Select</option>{options.map(option => <option key={option}>{option}</option>)}</select></label>)}</div><div className="stability-fields">{fields.map(field => <label key={field}>{field.replace(/[A-Z]/g, letter => ` ${letter}`).replace(/^./, letter => letter.toUpperCase())}<textarea value={docs[field] || ''} onChange={event => setDocs({ ...docs, [field]: event.target.value })} /></label>)}<label>Manufacturer documentation reference<input value={docs.manufacturerDocumentationReference} onChange={event => setDocs({ ...docs, manufacturerDocumentationReference: event.target.value })} /></label><label>Evidence reference<input value={docs.evidenceReference} onChange={event => setDocs({ ...docs, evidenceReference: event.target.value })} /></label></div><button className="stability-secondary" disabled={busy || !completeDocs} onClick={() => void saveDocs()}>Save documentation review</button></section>
    <section className="stability-section"><span className="stability-kicker">TEST SETUP</span><h2>Primary stability test</h2><div className="stability-setup"><div><small>Target</small><strong>0.50 × Max · {fmt(plan.targetLoad?.value, unit)}</strong><p>Recommended target; the actual load remains a tester observation.</p></div><label>Actual test load<input type="number" min="0" step="any" value={actualLoad} onChange={event => setActualLoad(event.target.value)} /><select value={loadUnit} onChange={event => setLoadUnit(event.target.value)}>{units.map(item => <option key={item}>{item}</option>)}</select></label><button className="stability-secondary" disabled={busy || !test.documentation || !actualLoad} onClick={() => void saveSetup()}>Save actual load</button></div></section>
    {phase2?.applicability === 'APPLICABLE' && <section className="stability-section"><span className="stability-kicker">A.4.12.2</span><h2>Printing / data-storage stability</h2><p>Manually disturb equilibrium once, then initiate the function immediately. Observe the indication for five seconds following the command.</p>{!test.printStorage?.commandStartedAt && <div className="stability-setup"><label>Function tested<select value={functionTested} onChange={event => setFunctionTested(event.target.value)}>{activeOperations.filter((item: string) => item === 'PRINT' || item === 'STORE').map((item: string) => <option key={item}>{item}</option>)}</select></label><label><input type="checkbox" checked={disturbed} onChange={event => setDisturbed(event.target.checked)} /> I manually disturbed the equilibrium.</label><label><input type="checkbox" checked={immediate} onChange={event => setImmediate(event.target.checked)} /> I initiated the command immediately.</label><button className="stability-primary" disabled={busy || !test.setup || !disturbed || !immediate} onClick={() => void startPrint()}><Clock3 size={15} /> Start five-second observation</button></div>}{test.printStorage?.commandStartedAt && test.printStorage?.status !== 'COMPLETED' && <div className="stability-observe"><strong>{Math.max(0, 5 - elapsed).toFixed(3)} s</strong><span>Server timestamp is authoritative; this timer is a display aid.</span><label>Printed / stored value<input type="number" step="any" value={printed} onChange={event => setPrinted(event.target.value)} /> {unit}</label><label>Observed indication sequence (comma-separated)<textarea value={sequence} onChange={event => setSequence(event.target.value)} placeholder="Enter the actual values observed during the five-second period" /></label><button className="stability-primary" disabled={busy || elapsed < 5 || !printed || !sequenceValues.length} onClick={() => void finishPrint()}>Evaluate stability sequence</button></div>}{test.printStorage?.status === 'COMPLETED' && <div className="stability-result-row"><span>Adjacent values <strong>{test.printStorage.evaluation?.adjacentValueCount ?? '—'}</strong></span><span>Printed value included <strong>{test.printStorage.evaluation?.printedValueIncluded ? 'YES' : 'NO'}</strong></span><strong>{test.printStorage.result}</strong></div>}</section>}
    {(phase('A.4.12.3')?.applicability === 'APPLICABLE' || phase('A.4.12.4')?.applicability === 'APPLICABLE') && <section className="stability-condition"><strong>Zero-setting / tare condition</strong><p>Automatic zero-setting / zero-tracking must be OFF while testing these functions. The tester must confirm the physical state for each repetition; the software cannot verify it.</p><label><input type="checkbox" checked={zeroTrackingOffConfirmed} onChange={event => setZeroTrackingOffConfirmed(event.target.checked)} /> Automatic zero-setting / zero-tracking is OFF.</label></section>}
    {(['A.4.12.3', 'A.4.12.4'] as const).map(code => { const item = phase(code); if (item?.applicability !== 'APPLICABLE') return null; const branch = code === 'A.4.12.3' ? test.zeroSetting : test.tare; const count = branch?.repetitions?.length || 0; return <section className="stability-section" key={code}><span className="stability-kicker">{code}</span><h2>{code === 'A.4.12.3' ? 'Zero-setting stability' : 'Tare-balancing stability'}</h2><p>This branch reuses the persisted {code === 'A.4.12.3' ? 'A.4.2.3' : 'A.4.6.2'} evidence; no duplicate measurements are entered here.</p><div className="stability-progress">{Array.from({ length: 5 }, (_, index) => <span key={index} className={index < count ? 'done' : index === count ? 'active' : 'locked'}>{index < count ? <Check size={13} /> : index === count ? index + 1 : <Lock size={13} />}</span>)}</div>{count < 5 && <button className="stability-secondary" disabled={busy || !test.setup || !zeroTrackingOffConfirmed || test.phases.find((p: any) => p.code === code)?.status === 'LOCKED'} onClick={() => void saveRepetition(code)}>Confirm repetition {repetition} / 5</button>}{count >= 5 && <strong>{branch.result}</strong>}</section>; })}
    {phase('A.4.12.5')?.applicability === 'APPLICABLE' && <section className="stability-section"><span className="stability-kicker">A.4.12.5</span><h2>Continuous-disturbance inhibition</h2><p>Confirm what was observed while continuous disturbance remained active. Applicable operations: {activeOperations.join(', ') || 'none'}.</p><div className="stability-operations">{activeOperations.map((operation: string) => <label key={operation}>{operation}<select value={continuous[operation] || ''} onChange={event => setContinuous({ ...continuous, [operation]: event.target.value })}><option value="">Select observed state</option><option>BLOCKED</option><option>EXECUTED</option></select></label>)}</div><button className="stability-secondary" disabled={busy || !activeOperations.length || activeOperations.some((operation: string) => !continuous[operation])} onClick={() => void saveContinuous()}>Save inhibition observations</button></section>}
    <section className="stability-section"><span className="stability-kicker">TRACEABILITY</span><p>Source: OIML R 76-1:2006 §4.4.2 / Annex A A.4.12. The print/data-storage sequence is evaluated against the adjacent-value stable-equilibrium criterion; zero and tare branches retain their A.4.2.3 and A.4.6.2 source evidence.</p>{test.status === 'IN_PROGRESS' && <button className="stability-primary" disabled={busy} onClick={() => void complete()}>Complete A.4.12</button>}{test.status === 'COMPLETED' && <Link className="stability-secondary" to={`/tester/reports/${reportId}/testing`}>Return to Testing</Link>}</section><EvidencePanel context={{ reportId, testId: 'A.4.12', instrumentId: data.report?.instrumentId, category: 'TEST_SETUP', evidenceType: 'stability_setup', label: 'A.4.12 · Stability · Test Setup', testName: 'Stability of Equilibrium', oimlReference: 'A.4.12' }} />{data.applicability?.status !== 'NOT_APPLICABLE' && <TestProcedureInfo testId="A.4.12" configuration={{ ...snapshot, activeOperations, printingCapability: snapshot.printingCapability, dataStorageCapability: snapshot.dataStorageCapability, zeroSettingCapability: snapshot.zeroSettingMethod, tareCapability: snapshot.tareDevice, mobileInstrument: snapshot.mobileInstrument, applicabilityStatus: data.applicability?.status }} />}
  </section></main>;
}
