import { useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import axios from 'axios';
import { ArrowLeft, ArrowRight, Check, Plus } from 'lucide-react';
import './report-workflow.css';

type Form = {
  applicationNumber: string; referenceMode: string; externalReference: string; organization: string; contactName: string; email: string; phone: string; address: string;
  manufacturer: string; model: string; serial: string; accuracyClass: string; indication: string; unit: string; min: string; max: string; e: string; d: string; software: string; loadCell: string; interfaces: string[]; notes: string;
  rangeType: string; intervalType: string; tareDevice: string; multipleIndicatingDevices: string; loadReceptorType: string; numberOfSupportPoints: string; usesElectricPower: string; powerSupplyType: string; mobileInstrument: string; portableRoadVehicleInstrument: string; zeroSettingMethod: string; zeroTracking: string; zeroIndicatingDevice: string; digitalIndication: string;
};

const blank: Form = {
  applicationNumber: '', referenceMode: 'generated', externalReference: '', organization: '', contactName: '', email: '', phone: '', address: '', manufacturer: '', model: '', serial: '', accuracyClass: '', indication: '', unit: 'g', min: '', max: '', e: '', d: '', software: '', loadCell: '', interfaces: [], notes: '', rangeType: '', intervalType: '', tareDevice: '', multipleIndicatingDevices: '', loadReceptorType: '', numberOfSupportPoints: '', usesElectricPower: '', powerSupplyType: '', mobileInstrument: '', portableRoadVehicleInstrument: '', zeroSettingMethod: '', zeroTracking: '', zeroIndicatingDevice: '', digitalIndication: '',
};

const steps = ['Application', 'Instrument', 'Instrument Configuration', 'Review & Submit'] as const;
const accuracyClasses = ['Class I', 'Class II', 'Class III', 'Class IIII'];
const indicationTypes = ['Self-indicating', 'Semi-self-indicating', 'Non-self-indicating'];
const massUnits = ['g', 'kg', 'mg', 't'];
const yesNo = ['Yes', 'No'];

function Field({ label, value, onChange, required = true, type = 'text', min, max, step }: { label: string; value: string; onChange: (v: string) => void; required?: boolean; type?: string; min?: string; max?: string; step?: string }) {
  return <label className="report-field"><span>{label}{required && <i> *</i>}</span><input type={type} min={min} max={max} step={step} value={value} onChange={event => onChange(event.target.value)} /></label>;
}

function SelectField({ label, value, onChange, options, required = true }: { label: string; value: string; onChange: (v: string) => void; options: string[]; required?: boolean }) {
  return <label className="report-field"><span>{label}{required && <i> *</i>}</span><select value={value} onChange={event => onChange(event.target.value)}><option value="">Select</option>{options.map(option => <option key={option} value={option}>{option}</option>)}</select></label>;
}

function TextArea({ label, value, onChange, required = false }: { label: string; value: string; onChange: (v: string) => void; required?: boolean }) {
  return <label className="report-field"><span>{label}{required && <i> *</i>}</span><textarea value={value} onChange={event => onChange(event.target.value)} /></label>;
}

const formatNumber = (value: string | number) => Number.isFinite(Number(value)) ? new Intl.NumberFormat('en-IN', { maximumFractionDigits: 6 }).format(Number(value)) : '—';

export default function TestReportWorkflow() {
  const nav = useNavigate();
  const [searchParams] = useSearchParams();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState(blank);
  const [existingInstruments, setExistingInstruments] = useState<any[]>([]);
  const [selectedInstrumentId, setSelectedInstrumentId] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [submittedReportId, setSubmittedReportId] = useState('');
  const set = (key: keyof Form, value: string | string[]) => setForm(current => ({ ...current, [key]: value }));
  useEffect(() => { void axios.get('/instruments').then(response => setExistingInstruments(response.data.instruments || [])).catch(() => {}); }, []);
  const selectExistingInstrument = async (id: string) => {
    setSelectedInstrumentId(id);
    if (!id) return;
    try {
      const response = await axios.get(`/instruments/${id}`);
      const instrument = response.data.instrument;
      setForm(current => ({ ...current, manufacturer: instrument.manufacturer, model: instrument.typeDesignation, serial: instrument.serialNumber, accuracyClass: instrument.accuracyClass, indication: instrument.indicationType, unit: instrument.unit || 'g', min: String(instrument.min), max: String(instrument.max), e: String(instrument.e), d: String(instrument.d), software: instrument.softwareVersion || '', loadCell: instrument.loadCellInformation || '', interfaces: instrument.interfaces ? String(instrument.interfaces).split(',').map((value: string) => value.trim()).filter(Boolean) : [], notes: instrument.additionalInformation || '', rangeType: instrument.rangeType, intervalType: instrument.intervalType, tareDevice: instrument.tareDevice, multipleIndicatingDevices: instrument.multipleIndicatingDevices ? 'Yes' : 'No', loadReceptorType: instrument.loadReceptorType, numberOfSupportPoints: instrument.numberOfSupportPoints == null ? '' : String(instrument.numberOfSupportPoints), usesElectricPower: instrument.usesElectricPower ? 'Yes' : 'No', powerSupplyType: instrument.powerSupplyType, mobileInstrument: instrument.mobileInstrument ? 'Yes' : 'No', portableRoadVehicleInstrument: instrument.portableRoadVehicleInstrument ? 'Yes' : 'No', zeroSettingMethod: instrument.zeroSettingMethod || '', zeroTracking: instrument.zeroTracking == null ? '' : instrument.zeroTracking ? 'Yes' : 'No', zeroIndicatingDevice: instrument.zeroIndicatingDevice == null ? '' : instrument.zeroIndicatingDevice ? 'Yes' : 'No', digitalIndication: instrument.digitalIndication == null ? '' : instrument.digitalIndication ? 'Yes' : 'No' }));
      setError('');
    } catch (e: any) { setError(e.response?.data?.message || 'Unable to load the selected instrument.'); }
  };
  useEffect(() => { const id = searchParams.get('instrumentId'); if (id) { setStep(1); void selectExistingInstrument(id); } }, [searchParams]);
  const emailValid = /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(form.email);
  const applicationInvalid = !form.organization.trim() || !form.contactName.trim() || !emailValid || !/^\d{10}$/.test(form.phone) || !form.address.trim() || (form.referenceMode === 'external' && !form.externalReference.trim());
  const min = Number(form.min); const max = Number(form.max); const eValue = Number(form.e); const dValue = Number(form.d);
  const calculatedN = Number.isFinite(max) && max > 0 && Number.isFinite(eValue) && eValue > 0 ? max / eValue : NaN;
  const instrumentInvalid = !form.manufacturer.trim() || !form.model.trim() || !form.serial.trim() || !accuracyClasses.includes(form.accuracyClass) || !indicationTypes.includes(form.indication) || form.min.trim() === '' || form.max.trim() === '' || form.e.trim() === '' || form.d.trim() === '' || !Number.isFinite(min) || min < 0 || !Number.isFinite(max) || max <= 0 || max <= min || !Number.isFinite(eValue) || eValue <= 0 || !Number.isFinite(dValue) || dValue <= 0 || !Number.isInteger(calculatedN) || calculatedN <= 0;
  const configurationInvalid = !['single-range', 'multiple-range'].includes(form.rangeType) || !['single-interval', 'multi-interval'].includes(form.intervalType) || !yesNo.includes(form.tareDevice) || !yesNo.includes(form.multipleIndicatingDevices) || !['normal platform', 'other / special configuration'].includes(form.loadReceptorType) || (form.numberOfSupportPoints.trim() !== '' && (!Number.isInteger(Number(form.numberOfSupportPoints)) || Number(form.numberOfSupportPoints) < 0)) || !yesNo.includes(form.usesElectricPower) || !['AC mains', 'DC / battery', 'Other', 'Not specified'].includes(form.powerSupplyType) || !yesNo.includes(form.mobileInstrument) || !yesNo.includes(form.portableRoadVehicleInstrument) || !['Non-automatic', 'Semi-automatic', 'Automatic'].includes(form.zeroSettingMethod) || !yesNo.includes(form.zeroTracking) || !yesNo.includes(form.zeroIndicatingDevice) || !yesNo.includes(form.digitalIndication);
  const generate = async () => {
    try { const response = await axios.post('/test-reports/application-number'); set('applicationNumber', response.data.applicationNumber); setError(''); }
    catch { setError('Unable to generate an application number right now.'); }
  };

  const next = () => {
    setError('');
    if (step === 0 && applicationInvalid) return setError('Complete the required Application fields. Check the email and enter a 10-digit Indian phone number.');
    if (step === 1 && instrumentInvalid) return setError('Complete the instrument fields and use valid values: Max must be greater than Min, and Max ÷ e must be a whole number.');
    if (step === 2 && configurationInvalid) return setError('Complete the required Instrument Configuration selections before continuing.');
    if (step < 3) return setStep(current => current + 1);
    void submit();
  };

  const submit = async () => {
    if (applicationInvalid || instrumentInvalid || configurationInvalid) return setError('Please complete the Application, Instrument, and Instrument Configuration sections before submitting.');
    setBusy(true);
    try {
      const response = await axios.post('/test-reports', {
        applicationNumber: form.applicationNumber,
        externalApplicationReference: form.externalReference,
        referenceSource: form.referenceMode,
        applicant: { name: form.organization, contactName: form.contactName, email: form.email, contactNumber: `+91 ${form.phone}`, address: form.address },
        manufacturer: { name: form.manufacturer, address: form.address },
        instrumentId: selectedInstrumentId || undefined,
        instrument: { typeDesignation: form.model, accuracyClass: form.accuracyClass, indicationType: form.indication, zeroSettingMethod: form.zeroSettingMethod, zeroTracking: form.zeroTracking === 'Yes', zeroIndicatingDevice: form.zeroIndicatingDevice === 'Yes', digitalIndication: form.digitalIndication === 'Yes', unit: form.unit, min, max, e: eValue, d: dValue, n: calculatedN, serialNumber: form.serial, softwareVersion: form.software, loadCellInformation: form.loadCell, interfaces: form.interfaces.join(', '), additionalInformation: form.notes, tareDevice: form.tareDevice, rangeType: form.rangeType, intervalType: form.intervalType, multipleIndicatingDevices: form.multipleIndicatingDevices === 'Yes', loadReceptorType: form.loadReceptorType, numberOfSupportPoints: form.numberOfSupportPoints.trim() === '' ? undefined : Number(form.numberOfSupportPoints), usesElectricPower: form.usesElectricPower === 'Yes', powerSupplyType: form.powerSupplyType, mobileInstrument: form.mobileInstrument === 'Yes', portableRoadVehicleInstrument: form.portableRoadVehicleInstrument === 'Yes' },
        testEquipment: [],
      });
      const createdReportId = response.data.report.testReportId;
      setSubmittedReportId(createdReportId);
      window.setTimeout(() => nav(`/tester/reports/${createdReportId}`), 900);
    } catch (submissionError: any) { setError(submissionError.response?.data?.message || 'Unable to submit the report.'); }
    finally { setBusy(false); }
  };

  if (submittedReportId) return <main className="report-page"><section className="report-card report-submitted"><div className="report-title"><span>REPORT SUBMITTED</span><h1>Report Submitted</h1><p>Your test report has been created successfully. Opening the report workspace…</p></div><div className="submitted-reference"><small>Test Report Number</small><strong>{submittedReportId}</strong></div></section></main>;
  const stepDescription = step === 0 ? 'Application and submission information.' : step === 1 ? 'Static instrument identification and technical characteristics.' : step === 2 ? 'Configuration characteristics used to determine the applicable OIML test route.' : 'Confirm the report setup before creating the test report.';
   return <main className="report-page"><header className="report-header"><Link to="/tester/dashboard">← Back to dashboard</Link><h1>New Test Report</h1><p>Prepare the application and instrument record before Verification.</p></header><div className="report-steps">{steps.map((name, index) => <button type="button" key={name} className={index === step ? 'current' : ''} disabled><span>{index + 1}</span>{name}</button>)}</div><section className="report-card"><div className="report-title"><span>STEP {step + 1} OF {steps.length} · REPORT SETUP</span><h2>{steps[step]}</h2><p>{stepDescription}</p></div>{step === 1 && existingInstruments.length > 0 && <div className="existing-instrument-picker"><label><span>Select Existing Instrument</span><select value={selectedInstrumentId} onChange={event => void selectExistingInstrument(event.target.value)}><option value="">Register a new instrument</option>{existingInstruments.map(item => <option key={item.instrument._id} value={item.instrument._id}>{item.instrument.typeDesignation} · {item.instrument.serialNumber}</option>)}</select></label>{selectedInstrumentId && <small>Using the persistent instrument record; its characteristics are loaded automatically.</small>}</div>}
    {step === 0 && <><h3>Application reference</h3><div className="reference-choice"><button type="button" className={form.referenceMode === 'generated' ? 'selected' : ''} onClick={() => { set('referenceMode', 'generated'); set('externalReference', ''); }}><strong>Generate internal reference</strong><small>Assigned securely by NAWI.</small></button><button type="button" className={form.referenceMode === 'external' ? 'selected' : ''} onClick={() => { set('referenceMode', 'external'); set('applicationNumber', ''); }}><strong>Use external reference</strong><small>Enter a reference supplied by another system.</small></button></div>{form.referenceMode === 'generated' ? <div className="application-number-option"><div><strong>Internal application number</strong><small>Generated from the secure server counter.</small>{form.applicationNumber && <b>{form.applicationNumber}</b>}</div><button type="button" className="secondary" onClick={generate}>{form.applicationNumber ? 'Generate another' : 'Generate application number'}<Plus /></button></div> : <div className="report-fields"><Field label="External Application / Submission Reference" value={form.externalReference} onChange={value => set('externalReference', value)} required={false} /></div>}<h3>Applicant / manufacturer</h3><div className="report-fields"><Field label="Manufacturer / Applicant Organization" value={form.organization} onChange={value => set('organization', value)} /><Field label="Contact Person Name" value={form.contactName} onChange={value => set('contactName', value)} /><Field label="Email" type="email" value={form.email} onChange={value => set('email', value)} /><label className="report-field"><span>Phone <i> *</i></span><div className="combined-phone"><span aria-hidden="true">🇮🇳</span><b>+91</b><input inputMode="numeric" maxLength={10} value={form.phone} onChange={event => set('phone', event.target.value.replace(/\D/g, ''))} placeholder="10-digit mobile number" /></div>{form.phone.length > 0 && form.phone.length !== 10 && <small className="field-error">Please enter a valid 10-digit Indian mobile number.</small>}</label><TextArea label="Address" value={form.address} onChange={value => set('address', value)} required /></div>{form.email.length > 0 && !emailValid && <small className="field-error">Please enter a valid email address.</small>}</>}
    {step === 1 && <><h3>Instrument identification</h3><div className="report-fields"><Field label="Manufacturer" value={form.manufacturer} onChange={value => set('manufacturer', value)} /><Field label="Type Designation / Model" value={form.model} onChange={value => set('model', value)} /><Field label="Serial Number" value={form.serial} onChange={value => set('serial', value)} /><SelectField label="Accuracy Class" value={form.accuracyClass} onChange={value => set('accuracyClass', value)} options={accuracyClasses} /><SelectField label="Indication Type" value={form.indication} onChange={value => set('indication', value)} options={indicationTypes} /><SelectField label="Instrument Mass Unit" value={form.unit} onChange={value => set('unit', value)} options={massUnits} /></div><h3>Metrological characteristics ({form.unit})</h3><div className="report-fields"><Field label={`Min (${form.unit})`} type="number" min="0" step="any" value={form.min} onChange={value => set('min', value)} /><Field label={`Max (${form.unit})`} type="number" min="0" step="any" value={form.max} onChange={value => set('max', value)} /><Field label={`e (${form.unit})`} type="number" min="0" step="any" value={form.e} onChange={value => set('e', value)} /><Field label={`d (${form.unit})`} type="number" min="0" step="any" value={form.d} onChange={value => set('d', value)} /><label className="report-field"><span>Number of verification scale intervals (n)</span><input type="text" value={Number.isInteger(calculatedN) ? formatNumber(calculatedN) : ''} readOnly placeholder="Calculated from Max ÷ e" /><small className="field-help">Calculated from Max ÷ e; n is dimensionless and is not entered manually.</small></label></div><h3>Software &amp; electronics</h3><div className="report-fields"><Field label="Software / Firmware Version" required={false} value={form.software} onChange={value => set('software', value)} /><Field label="Load Cell / Weighing Module Information" required={false} value={form.loadCell} onChange={value => set('loadCell', value)} /><TextArea label="Additional Technical Information / Notes" value={form.notes} onChange={value => set('notes', value)} /></div><h3>Interfaces</h3><div className="check-grid">{['USB', 'RS-232', 'RS-485', 'Ethernet', 'Modbus', 'Other'].map(name => <label key={name}><input type="checkbox" checked={form.interfaces.includes(name)} onChange={event => set('interfaces', event.target.checked ? [...form.interfaces, name] : form.interfaces.filter(item => item !== name))} />{name}</label>)}</div></>}
    {step === 2 && <><h3>Range and interval configuration</h3><div className="report-fields"><SelectField label="Range Configuration" value={form.rangeType} onChange={value => set('rangeType', value)} options={['single-range', 'multiple-range']} /><SelectField label="Interval Configuration" value={form.intervalType} onChange={value => set('intervalType', value)} options={['single-interval', 'multi-interval']} /></div><h3>Zero-setting characteristics</h3><div className="report-fields"><SelectField label="Zero-setting Method" value={form.zeroSettingMethod} onChange={value => set('zeroSettingMethod', value)} options={['Non-automatic', 'Semi-automatic', 'Automatic']} /><SelectField label="Zero-tracking" value={form.zeroTracking} onChange={value => set('zeroTracking', value)} options={yesNo} /><SelectField label="Zero-indicating Device" value={form.zeroIndicatingDevice} onChange={value => set('zeroIndicatingDevice', value)} options={yesNo} /><SelectField label="Digital Indication" value={form.digitalIndication} onChange={value => set('digitalIndication', value)} options={yesNo} /></div><h3>Instrument devices and construction</h3><div className="report-fields"><SelectField label="Tare Device" value={form.tareDevice} onChange={value => set('tareDevice', value)} options={yesNo} /><SelectField label="Multiple Indicating Devices" value={form.multipleIndicatingDevices} onChange={value => set('multipleIndicatingDevices', value)} options={yesNo} /><SelectField label="Load Receptor Configuration" value={form.loadReceptorType} onChange={value => set('loadReceptorType', value)} options={['normal platform', 'other / special configuration']} /><Field label="Number of Support Points" type="number" min="0" step="1" required={false} value={form.numberOfSupportPoints} onChange={value => set('numberOfSupportPoints', value)} /></div><h3>Power and mobility</h3><div className="report-fields"><SelectField label="Electrically Powered" value={form.usesElectricPower} onChange={value => set('usesElectricPower', value)} options={yesNo} /><SelectField label="Power Supply" value={form.powerSupplyType} onChange={value => set('powerSupplyType', value)} options={['AC mains', 'DC / battery', 'Other', 'Not specified']} /><SelectField label="Mobile Instrument" value={form.mobileInstrument} onChange={value => set('mobileInstrument', value)} options={yesNo} /><SelectField label="Portable Road-Vehicle Weighbridge" value={form.portableRoadVehicleInstrument} onChange={value => set('portableRoadVehicleInstrument', value)} options={yesNo} /></div><p className="field-help">These characteristics are saved with the report profile and are used by the applicability engine. Advanced test procedures remain outside this setup step.</p></>}
    {step === 3 && <><h3>Application</h3><div className="review-summary"><div><small>Application reference</small><strong>{form.referenceMode === 'external' ? form.externalReference : form.applicationNumber || 'Generated on submission'}</strong></div><div><small>Applicant / Manufacturer</small><strong>{form.organization}</strong></div><div><small>Contact</small><strong>{form.contactName} · {form.email}</strong></div><div><small>Phone</small><strong>+91 {form.phone}</strong></div><div className="span-two"><small>Address</small><strong>{form.address}</strong></div></div><h3>Instrument</h3><div className="review-summary"><div><small>Manufacturer</small><strong>{form.manufacturer}</strong></div><div><small>Type Designation / Model</small><strong>{form.model}</strong></div><div><small>Serial Number</small><strong>{form.serial}</strong></div><div><small>Accuracy Class</small><strong>{form.accuracyClass}</strong></div><div><small>Indication Type</small><strong>{form.indication}</strong></div><div><small>Instrument Mass Unit</small><strong>{form.unit}</strong></div><div><small>Min / Max</small><strong>{formatNumber(min)} {form.unit} / {formatNumber(max)} {form.unit}</strong></div><div><small>e / d / n</small><strong>{formatNumber(eValue)} {form.unit} / {formatNumber(dValue)} {form.unit} / {formatNumber(calculatedN)}</strong></div><div><small>Software / Firmware</small><strong>{form.software || '—'}</strong></div><div><small>Load Cell / Module</small><strong>{form.loadCell || '—'}</strong></div><div><small>Interfaces / Notes</small><strong>{[form.interfaces.join(', '), form.notes].filter(Boolean).join(' · ') || '—'}</strong></div></div><h3>Instrument configuration</h3><div className="review-summary"><div><small>Range / interval</small><strong>{form.rangeType} / {form.intervalType}</strong></div><div><small>Tare / multiple indicating devices</small><strong>{form.tareDevice} / {form.multipleIndicatingDevices}</strong></div><div><small>Load receptor / support points</small><strong>{form.loadReceptorType} / {form.numberOfSupportPoints || 'Not specified'}</strong></div><div><small>Power / supply</small><strong>{form.usesElectricPower} / {form.powerSupplyType}</strong></div><div><small>Mobile / portable road-vehicle</small><strong>{form.mobileInstrument} / {form.portableRoadVehicleInstrument}</strong></div></div></>}
    {error && <div className="error">{error}</div>}<div className="report-actions">{step > 0 && <button className="secondary" onClick={() => setStep(current => current - 1)}><ArrowLeft />Back</button>}<button className="primary" disabled={busy} onClick={next}>{busy ? step === 3 ? 'Submitting…' : 'Saving…' : step === 1 ? 'Continue to Configuration' : step === 2 ? 'Save & Continue to Review' : step === 3 ? 'Submit Report' : 'Continue'}{step === 3 ? <Check /> : <ArrowRight />}</button></div></section></main>;
}
