import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { FileText, Plus } from 'lucide-react';
import './verification.css';

export default function TesterReports() {
  const [reports, setReports] = useState<any[]>([]); const [error, setError] = useState(''); const nav = useNavigate();
  useEffect(() => { axios.get('/test-reports').then(response => setReports(response.data.reports || [])).catch(error => setError(error.response?.data?.message || 'Unable to load test reports.')); }, []);
  return <main className="reports-page"><section className="reports-content"><div className="reports-heading"><div><span className="technical-label">TESTER WORKSPACE</span><h1>Test Reports</h1><p>Open a report to continue its examination record.</p></div><button className="report-primary" onClick={() => nav('/tester/new-report')}><Plus size={17} /> New Test Report</button></div>{error && <div className="report-error">{error}</div>}<section className="reports-table-wrap">{reports.length ? <table className="reports-table"><thead><tr><th>Test Report Number</th><th>Application / External Reference</th><th>Manufacturer / Applicant</th><th>Instrument</th><th>Serial Number</th><th>Assigned Tester</th><th>Current Stage</th><th>Status</th><th>Created</th><th>Updated</th></tr></thead><tbody>{reports.map(report => <tr key={report.testReportId} onClick={() => nav(`/tester/reports/${report.testReportId}`)} tabIndex={0} onKeyDown={event => { if (event.key === 'Enter') nav(`/tester/reports/${report.testReportId}`); }}><td><strong>{report.testReportId}</strong></td><td>{report.externalApplicationReference || report.applicationNumber || '—'}</td><td>{report.manufacturer?.name || report.applicant?.name || '—'}</td><td>{report.instrument?.typeDesignation || '—'}</td><td>{report.instrument?.serialNumber || '—'}</td><td>{report.testerNameSnapshot || 'Assigned when verification starts'}</td><td>{report.stage || 'APPLICATION'}</td><td><span className="report-status">{String(report.status || '').replace(/_/g, ' ')}</span></td><td>{report.createdAt ? new Date(report.createdAt).toLocaleDateString() : '—'}</td><td>{report.updatedAt ? new Date(report.updatedAt).toLocaleDateString() : '—'}</td></tr>)}</tbody></table> : <div className="reports-empty"><FileText size={26} /><h2>No test reports yet</h2><p>Start a new test report to create the first application record.</p><button className="report-primary" onClick={() => nav('/tester/new-report')}><Plus size={16} /> New Test Report</button></div>}</section></section></main>;
}
