import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { ArrowLeft, Check, Lock, Play, Save } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';
import './zero-checking.css';
import TestProcedureInfo from '../../guidance/TestProcedureInfo';
import { buildExpectedZeroIndicatorSequence, convertZeroIndicatorMass, deriveZeroIndicatorIncrement, formatZeroIndicatorValue, type ZeroIndicatorObservation } from './zeroIndicatorObservations';

const units = ['mg', 'g', 'kg', 't'];
const phases = [
  ['A.4.2.1', 'Zero-setting Range'],
  ['A.4.2.2', 'Zero Indicator'],
  ['A.4.2.3', 'Accuracy of Zero-setting'],
] as const;

type FormState = { [key: string]: string };
const empty = { unit: 'g', startingZeroState: '', appliedLoad: '', zeroRestored: '', observedPositiveRange: '', observedNegativeRange: '', initialLoadApplied: '', maximumLoadRemovedWhileZeroRestored: '', nextRemovalFailedToRestoreZero: '', startingIndication: '', observedLowerRange: '', observedUpperRange: '', zeroIndicationI0: '', deltaL0: '', loadL: '', indicationI: '', deltaL: '', notes: '' };

export default function ZeroCheckingWorkspace() {
  const { reportId = '' } = useParams();
  const nav = useNavigate();
  const [report, setReport] = useState<any>();
  const [applicability, setApplicability] = useState<any>();
  const [test, setTest] = useState<any>();
  const [form, setForm] = useState<FormState>(empty);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  const load = async () => {
    try { const response = await axios.get(`/test-reports/${reportId}/zero-checking`); setReport(response.data.report); setApplicability(response.data.applicability); setTest(response.data.test); if (response.data.test?.instrumentSnapshot?.unit) setForm(current => ({ ...current, unit: response.data.test.instrumentSnapshot.unit })); } catch (e: any) { setError(e.response?.data?.message || 'Unable to load Checking of Zero.'); }
  };
  useEffect(() => { void load(); }, [reportId]);
  const instrumentUnit = test?.instrumentSnapshot?.unit || report?.instrument?.unit || 'g';
  const applicablePhases = useMemo(() => (test?.phases || applicability?.phases || []).filter((phase: any) => phase.status === 'APPLICABLE' || phase.applicability === 'APPLICABLE'), [test?.phases, applicability?.phases]);
  const activePhase = test?.phases?.find((phase: any) => phase.applicability === 'APPLICABLE' && phase.status !== 'COMPLETED');
  const begin = async () => { setBusy(true); try { const response = await axios.post(`/test-reports/${reportId}/zero-checking/start`); setReport(response.data.report); setApplicability(response.data.applicability); setTest(response.data.test); setError(''); } catch (e: any) { setError(e.response?.data?.message || 'Unable to start Checking of Zero.'); } finally { setBusy(false); } };
  const set = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }));
  const number = (key: string) => form[key] === '' ? undefined : Number(form[key]);
  const savePhase = async (indicationObservations?: ZeroIndicatorObservation[]) => {
    if (!activePhase) return;
    setBusy(true);
    try {
      const body: any = { unit: form.unit || instrumentUnit, notes: form.notes };
      if (activePhase.code === 'A.4.2.1') {
        if (test?.instrumentSnapshot?.zeroSettingMethod === 'Automatic') Object.assign(body, { startingZeroState: form.startingZeroState, initialLoadApplied: Number(form.initialLoadApplied), maximumLoadRemovedWhileZeroRestored: Number(form.maximumLoadRemovedWhileZeroRestored), nextRemovalFailedToRestoreZero: form.nextRemovalFailedToRestoreZero });
        else Object.assign(body, { startingZeroState: form.startingZeroState, appliedLoad: Number(form.appliedLoad), zeroRestored: form.zeroRestored, observedPositiveRange: Number(form.observedPositiveRange), observedNegativeRange: number('observedNegativeRange') });
      }
      if (activePhase.code === 'A.4.2.2') Object.assign(body, { startingIndication: Number(form.startingIndication), indicationObservations, observedLowerRange: Number(form.observedLowerRange), observedUpperRange: Number(form.observedUpperRange) });
      if (activePhase.code === 'A.4.2.3') Object.assign(body, { zeroIndicationI0: Number(form.zeroIndicationI0), deltaL0: Number(form.deltaL0), loadL: Number(form.loadL), indicationI: Number(form.indicationI), deltaL: Number(form.deltaL) });
      const response = await axios.patch(`/test-reports/${reportId}/zero-checking/phases/${activePhase.code}`, body); setTest(response.data.test); setError('');
    } catch (e: any) { setError(e.response?.data?.message || 'Unable to save this A.4.2 phase.'); } finally { setBusy(false); }
  };
  if (!report) return <main className="zero-checking-page"><div className="zero-checking-loading">{error || 'Loading Checking of Zero…'}</div></main>;
  if (!applicability || applicability.status !== 'APPLICABLE') return <main className="zero-checking-page"><Header reportId={reportId} /><section className="zero-checking-content"><div className="zero-checking-error"><h1>Checking of Zero unavailable</h1><p>{applicability?.reason || 'Instrument configuration is required before this procedure can start.'}</p><Link className="zero-secondary" to={`/tester/reports/${reportId}/testing`}>Back to Testing</Link></div></section></main>;
  return <main className="zero-checking-page"><Header reportId={reportId} /><section className="zero-checking-content">
    <div className="zero-checking-heading"><div><span className="technical-label">A.4.2 · OIML R 76-1:2006 ANNEX A</span><h1>Checking of Zero</h1><p>{report.testReportId} · Follow the applicable zero-setting procedure and record the observed evidence.</p></div><span className={`zero-status ${test?.status === 'COMPLETED' ? 'complete' : ''}`}>{test?.status === 'COMPLETED' ? `COMPLETED · ${test.result}` : test ? 'IN PROGRESS' : 'NOT STARTED'}</span></div>
    <section className="zero-stepper" aria-label="Checking of Zero phases">{phases.map(([code, name], index) => { const phase = test?.phases?.find((item: any) => item.code === code) || applicability.phases?.find((item: any) => item.code === code); const status = phase?.status || phase?.applicability || 'REQUIRES_CONFIGURATION'; return <div className={`zero-step ${status.toLowerCase()}`} key={code}><span>{status === 'COMPLETED' ? <Check size={16} /> : status === 'LOCKED' ? <Lock size={15} /> : index + 1}</span><div><strong>Phase {index + 1}</strong><b>{name}</b><small>{code} · {status.replace(/_/g, ' ')}</small></div></div>; })}</section>
    {!test ? <section className="zero-panel zero-start"><Play size={24} /><div><h2>Begin the zero-checking procedure</h2><p>The test will create an editable record for the applicable A.4.2 phases. No observations are generated automatically.</p></div><button className="zero-primary" onClick={begin} disabled={busy}><Play size={16} /> Begin Checking of Zero</button></section> : <>
      {test.status === 'COMPLETED' ? <section className="zero-panel zero-complete"><Check size={25} /><div><h2>Checking of Zero completed</h2><p>All applicable phases have been recorded. Result: <strong>{test.result}</strong>.</p>{test.phases?.find((phase: any) => phase.code === 'A.4.2.3')?.calculations && <CalculationDetails calculations={test.phases.find((phase: any) => phase.code === 'A.4.2.3').calculations} unit={instrumentUnit} />}<Link className="zero-primary" to={`/tester/reports/${reportId}/testing`}>Return to Test Route</Link></div></section> : activePhase && <PhaseForm key={activePhase.code} phase={activePhase} form={form} set={set} instrumentUnit={instrumentUnit} d={Number(test?.instrumentSnapshot?.d)} max={Number(test?.instrumentSnapshot?.max)} automaticZeroSetting={test?.instrumentSnapshot?.zeroSettingMethod === 'Automatic'} onSave={savePhase} busy={busy} />}
      <section className="zero-panel zero-trace"><span className="technical-label">TRACEABILITY</span><p>OIML R 76-1:2006 Annex A A.4.2. A.4.2.3 uses the shared A.4.4.3 changeover calculation and the existing initial-verification MPE/compliance services.</p></section>
      <TestProcedureInfo testId={activePhase?.code || 'A.4.2.3'} configuration={{ ...(test?.instrumentSnapshot || report?.instrument || {}), applicabilityStatus: applicability.status }} />
    </>}
    {error && <div className="zero-error">{error}</div>}
  </section></main>;
}

function Header({ reportId }: { reportId: string }) { return <header className="zero-top"><Link to={`/tester/reports/${reportId}/testing`}><ArrowLeft size={16} /> Testing route</Link><div className="zero-brand"><strong>NAWI</strong><span>TEST &amp; REPORT SYSTEM</span></div><Link to="/tester/reports">All Test Reports</Link></header>; }

function PhaseForm({ phase, form, set, instrumentUnit, d, max, automaticZeroSetting, onSave, busy }: { phase: any; form: FormState; set: (key: string, value: string) => void; instrumentUnit: string; d: number; max: number; automaticZeroSetting: boolean; onSave: (indicationObservations?: ZeroIndicatorObservation[]) => void; busy: boolean }) {
  const saved = phase.observations || {};
  const savedObservations = Array.isArray(saved.indicationObservations) ? saved.indicationObservations : [];
  const [observations, setObservations] = useState<ZeroIndicatorObservation[]>(savedObservations.map((observation: any, index: number) => ({ sequence: Number(observation.sequence) || index + 1, value: Number(observation.inputValue ?? observation.value), unit: observation.inputUnit || observation.unit || instrumentUnit, observedAt: observation.observedAt ? new Date(observation.observedAt).toISOString() : undefined })));
  const [nextIndication, setNextIndication] = useState('');
  const observationUnit = form.unit || instrumentUnit;
  const displayD = convertZeroIndicatorMass(d, instrumentUnit, observationUnit);
  const increment = deriveZeroIndicatorIncrement(displayD);
  const expected = useMemo(() => form.startingIndication.trim() === '' ? [] : buildExpectedZeroIndicatorSequence(Number(form.startingIndication), displayD), [form.startingIndication, displayD]);
  const addObservation = () => {
    if (nextIndication.trim() === '' || !Number.isFinite(Number(nextIndication))) return;
    setObservations(current => [...current, { sequence: current.length + 1, value: Number(nextIndication), unit: form.unit || instrumentUnit, observedAt: new Date().toISOString() }]);
    setNextIndication('');
  };
  const deleteObservation = (sequence: number) => setObservations(current => current.filter(observation => observation.sequence !== sequence).map((observation, index) => ({ ...observation, sequence: index + 1 })));
  const savedValue = (key: string) => form[key] || saved[key] || '';
  return <section className="zero-panel zero-phase"><div className="zero-phase-heading"><div><span className="technical-label">{phase.code}</span><h2>{phase.name}</h2><p>{phase.code === 'A.4.2.1' ? automaticZeroSetting ? 'For automatic zero-setting, remove weights in small amounts and allow the automatic device time to restore zero after each removal.' : 'Observe the zero-setting range for the configured zero-setting arrangement.' : phase.code === 'A.4.2.2' ? 'Use additions equivalent to approximately 1/10 d and record the actual digital zero-indicator readings in order.' : <>Record the changeover observation; P, E, <span className="math-variable" aria-label="E sub zero">E<sub>0</sub></span>, <span className="math-variable" aria-label="E sub c">E<sub>c</sub></span>, and MPE are calculated automatically.</>}</p></div><span className="zero-phase-badge">AVAILABLE</span></div>
    {phase.code === 'A.4.2.1' && automaticZeroSetting && <><div className="zero-rule-note"><strong>Automatic zero-setting range</strong><p>R76 A.4.2.1.3: the range is the maximum load that can be removed while the automatic zero-setting device still resets the indication to zero.</p><div><span>Overall zero-setting / zero-tracking reference</span><b>≤ 4% of Max ({Number.isFinite(max) ? `${format(max * 0.04)} ${instrumentUnit}` : '—'})</b><span>Initial zero-setting device reference</span><b>≤ 20% of Max ({Number.isFinite(max) ? `${format(max * 0.2)} ${instrumentUnit}` : '—'})</b></div></div><div className="zero-fields"><Field label="Indication / zero state before observation" value={savedValue('startingZeroState')} set={value => set('startingZeroState', value)} /><Field label={`Initial load applied to bring instrument to zero (${form.unit || instrumentUnit})`} type="number" min="0" value={savedValue('initialLoadApplied')} set={value => set('initialLoadApplied', value)} /><Field label={`Maximum load removed while zero was automatically restored (${form.unit || instrumentUnit})`} type="number" min="0" value={savedValue('maximumLoadRemovedWhileZeroRestored')} set={value => set('maximumLoadRemovedWhileZeroRestored', value)} /><Select label="Next removal failed to restore zero?" value={savedValue('nextRemovalFailedToRestoreZero')} options={['Yes', 'No']} set={value => set('nextRemovalFailedToRestoreZero', value)} /><div className="zero-derived-field"><span>Observed zero-setting range</span><strong>{savedValue('maximumLoadRemovedWhileZeroRestored') ? `${savedValue('maximumLoadRemovedWhileZeroRestored')} ${form.unit || instrumentUnit}` : 'Enter the maximum successful removal'}</strong><small>Derived from the maximum successful automatic restoration observation; not an automatic conformity result.</small></div></div></>}
    {phase.code === 'A.4.2.1' && !automaticZeroSetting && <div className="zero-fields"><Field label="Starting zero state" value={savedValue('startingZeroState')} set={value => set('startingZeroState', value)} /><Field label={`Applied / removed load (${form.unit || instrumentUnit})`} type="number" min="0" value={savedValue('appliedLoad')} set={value => set('appliedLoad', value)} /><Select label="Was zero successfully restored?" value={savedValue('zeroRestored')} options={['Yes', 'No']} set={value => set('zeroRestored', value)} /><Field label={`Observed positive zero-setting range (${form.unit || instrumentUnit})`} type="number" min="0" value={savedValue('observedPositiveRange')} set={value => set('observedPositiveRange', value)} /><Field label={`Observed negative zero-setting range magnitude (${form.unit || instrumentUnit}) · optional`} type="number" min="0" value={savedValue('observedNegativeRange')} set={value => set('observedNegativeRange', value)} /></div>}
    {phase.code === 'A.4.2.2' && <div className="zero-indicator-workspace">
      <div className="zero-indicator-metrics"><div><span>Scale interval d</span><strong>{Number.isFinite(displayD) ? `${formatZeroIndicatorValue(displayD, displayD)} ${observationUnit}` : '—'}</strong></div><div><span>Observation increment</span><strong>{increment === undefined ? '—' : `${formatZeroIndicatorValue(increment, displayD)} ${observationUnit}`}</strong><small>d / 10 · derived from instrument configuration</small></div></div>
      <div className="zero-fields"><Field label={`Starting indication (${observationUnit})`} type="number" value={savedValue('startingIndication')} set={value => set('startingIndication', value)} /><div className="zero-derived-field"><span>Expected progression (guidance only)</span><strong>{expected.length ? `${formatZeroIndicatorValue(expected[0], displayD)} → ${formatZeroIndicatorValue(expected[expected.length - 1], displayD)} ${observationUnit}` : 'Enter the starting indication'}</strong><small>Actual readings below are never generated from this guidance.</small></div><Field label={`Observed lower zero range — signed indication (${observationUnit})`} type="number" value={savedValue('observedLowerRange')} set={value => set('observedLowerRange', value)} /><Field label={`Observed upper zero range — signed indication (${observationUnit})`} type="number" value={savedValue('observedUpperRange')} set={value => set('observedUpperRange', value)} /></div>
      <div className="zero-observation-entry"><label><span>Current / next indication ({form.unit || instrumentUnit})</span><input type="number" step="any" value={nextIndication} onChange={event => setNextIndication(event.target.value)} /></label><button type="button" className="zero-secondary" onClick={addObservation} disabled={!nextIndication.trim() || !Number.isFinite(Number(nextIndication))}>Record indication</button></div>
      <div className="zero-observation-header"><div><strong>Recorded observations</strong><span>{observations.length} recorded · actual tester readings</span></div><span>Expected indication is guidance</span></div>
      <div className="zero-observation-grid"><div className="zero-observation-grid-head"><span>#</span><span>Expected indication</span><span>Actual indication</span><span>Action</span></div>{(expected.length || observations.length ? Array.from({ length: Math.max(expected.length, observations.length) }, (_, index) => index) : []).map(index => { const actual = observations[index]; const expectedValue = expected[index]; return <div className="zero-observation-grid-row" key={actual?.sequence || `expected-${index}`}><span>{index + 1}</span><span>{expectedValue === undefined ? '—' : `${formatZeroIndicatorValue(expectedValue, displayD)} ${observationUnit}`}</span><span>{actual ? `${formatZeroIndicatorValue(actual.value, displayD)} ${actual.unit}` : 'Not recorded'}</span><button type="button" className="zero-observation-delete" onClick={() => actual && deleteObservation(actual.sequence)} disabled={!actual}>Delete</button></div>; })}</div>
    </div>}
    {phase.code === 'A.4.2.3' && <><div className="zero-fields"><Field label={<>Zero indication <span className="math-variable" aria-label="I sub zero">I<sub>0</sub></span> ({form.unit || instrumentUnit})</>} type="number" value={form.zeroIndicationI0} set={value => set('zeroIndicationI0', value)} /><Field label={<>Additional load <span className="math-variable" aria-label="delta L sub zero">ΔL<sub>0</sub></span> ({form.unit || instrumentUnit})</>} type="number" min="0" value={form.deltaL0} set={value => set('deltaL0', value)} /><Field label={`Test load L (${form.unit || instrumentUnit})`} type="number" min="0" value={form.loadL} set={value => set('loadL', value)} /><Field label={`Indication I (${form.unit || instrumentUnit})`} type="number" value={form.indicationI} set={value => set('indicationI', value)} /><Field label={`Additional load ΔL (${form.unit || instrumentUnit})`} type="number" min="0" value={form.deltaL} set={value => set('deltaL', value)} /></div>{phase.calculations && <CalculationDetails calculations={phase.calculations} unit={instrumentUnit} />}</>}
      <label className="zero-notes"><span>Operator notes (optional)</span><textarea value={form.notes || saved.notes || ''} onChange={event => set('notes', event.target.value)} /></label><div className="zero-phase-actions"><label>Observation unit<select value={form.unit || instrumentUnit} onChange={event => set('unit', event.target.value)}>{units.map(unit => <option key={unit}>{unit}</option>)}</select></label><button className="zero-primary" onClick={() => onSave(phase.code === 'A.4.2.2' ? observations : undefined)} disabled={busy || (phase.code === 'A.4.2.2' && (observations.length === 0 || !form.startingIndication.trim() || !Number.isFinite(Number(form.startingIndication)) || !form.observedLowerRange.trim() || !form.observedUpperRange.trim() || !Number.isFinite(Number(form.observedLowerRange)) || !Number.isFinite(Number(form.observedUpperRange))))}><Save size={16} /> Save &amp; Complete Phase</button></div>
  </section>;
}

function Field({ label, value, set, type = 'text', min }: { label: ReactNode; value: string; set: (value: string) => void; type?: string; min?: string }) { return <label><span>{label}</span><input type={type} min={min} step="any" value={value} onChange={event => set(event.target.value)} /></label>; }
function Select({ label, value, options, set }: { label: string; value: string; options: string[]; set: (value: string) => void }) { return <label><span>{label}</span><select value={value} onChange={event => set(event.target.value)}><option value="">Select</option>{options.map(option => <option key={option}>{option}</option>)}</select></label>; }
function CalculationDetails({ calculations, unit }: { calculations: any; unit: string }) { return <div className="zero-calculations"><span>Calculated A.4.2.3 result</span><div><b>P</b><strong>{format(calculations.trueIndicationP)} {unit}</strong><b>E</b><strong>{format(calculations.rawErrorE)} {unit}</strong><b><span className="math-variable" aria-label="E sub zero">E<sub>0</sub></span></b><strong>{format(calculations.calculatedE0)} {unit}</strong><b><span className="math-variable" aria-label="E sub c">E<sub>c</sub></span></b><strong>{format(calculations.correctedErrorEc)} {unit}</strong><b>MPE</b><strong>±{format(calculations.mpeValue)} {unit}</strong><b>Result</b><strong className={String(calculations.complianceResult).toLowerCase()}>{calculations.complianceResult}</strong></div><small>{calculations.ruleReference} · {calculations.rangeLabel}</small></div>; }
function format(value: unknown) { return Number.isFinite(Number(value)) ? Number(value).toFixed(4) : '—'; }
