import { useEffect, useState } from 'react';
import { ArrowLeft, Check, Lock, Play, Save } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';
import './influence-factors.css';
import TestProcedureInfo from '../../guidance/TestProcedureInfo';

const API = (id: string, suffix = '') => `/test-reports/${id}/influence-factors${suffix}`;
const num = (value: unknown) => value === '' || value === undefined ? undefined : Number(value);

export default function InfluenceFactorsWorkspace() {
  const { reportId = '' } = useParams();
  const nav = useNavigate();
  const [data, setData] = useState<any>();
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const load = () => axios.get(API(reportId)).then(response => setData(response.data)).catch((e: any) => setError(e.response?.data?.message || 'Unable to load Influence Factors.'));
  useEffect(() => { void load(); }, [reportId]);
  const test = data?.test;
  const applicability = data?.applicability;
  const snapshot = test?.instrumentSnapshot || data?.report?.instrument || {};
  const phases = test?.phases || applicability?.branches || [];
  const active = phases.find((phase: any) => phase.status === 'AVAILABLE' || phase.status === 'IN_PROGRESS');

  const start = async () => { setBusy(true); setError(''); try { const response = await axios.post(API(reportId, '/start')); setData((current: any) => ({ ...current, ...response.data, test: response.data.test })); } catch (e: any) { setError(e.response?.data?.message || 'Unable to start Influence Factors.'); } finally { setBusy(false); } };
  const saveSetup = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); try { const body = Object.fromEntries(new FormData(event.currentTarget)); await axios.patch(API(reportId, '/setup'), { environmentalConditionsStableConfirmed: body.environmentalConditionsStableConfirmed === 'on', notes: body.notes || '' }); await load(); } catch (e: any) { setError(e.response?.data?.message || 'Unable to save A.5 setup.'); } finally { setBusy(false); } };

  if (!data) return <main className="influence-page"><div className="influence-loading">{error || 'Loading Influence Factors…'}</div></main>;
  return <main className="influence-page">
    <header className="workspace-top"><Link to={`/tester/reports/${reportId}/testing`}><ArrowLeft size={16} /> A.4 Performance Tests</Link><div className="workspace-brand"><strong>NAWI</strong><span>TEST &amp; REPORT SYSTEM</span></div><span className="influence-route-label">ROUTE 2 OF 3 · A.5</span></header>
    <section className="influence-content">
      <div className="influence-heading"><div><span className="technical-label">ANNEX A · INFLUENCE FACTORS</span><h1>A.5 Influence Factors</h1><p>Configuration-driven environmental, electrical, and tilt procedures.</p></div><span className={`influence-badge ${test?.status === 'COMPLETED' ? 'complete' : ''}`}>{test?.result || applicability?.status || 'READY'}</span></div>
      {error && <div className="influence-error">{error}</div>}
      <section className="influence-context"><div><span className="technical-label">INSTRUMENT CONTEXT</span><h2>{snapshot.typeDesignation || 'Instrument'}</h2></div><div className="influence-context-grid"><span><b>Class</b>{snapshot.accuracyClass || '—'}</span><span><b>Max</b>{snapshot.max ?? '—'} {snapshot.unit || 'g'}</span><span><b>Min</b>{snapshot.min ?? '—'} {snapshot.unit || 'g'}</span><span><b>e / d</b>{snapshot.e ?? '—'} / {snapshot.d ?? '—'} {snapshot.unit || 'g'}</span><span><b>Power</b>{snapshot.powerSourceType || snapshot.powerSupplyType || '—'}</span><span><b>Nominal</b>{snapshot.nominalVoltage ? `${snapshot.nominalVoltage} V` : '—'}</span></div></section>
      {!test && <section className="influence-start"><span className="technical-label">A.5 ROUTE</span><h2>Influence Factors setup</h2><p>{applicability?.reason || 'The applicable A.5 branches are determined by the saved instrument profile.'}</p>{applicability?.branches?.map((branch: any) => <div className="influence-branch-preview" key={branch.code}><strong>{branch.code} · {branch.name}</strong><span>{branch.status.replace(/_/g, ' ')} · {branch.reason}</span></div>)}{applicability?.status === 'APPLICABLE' ? <button className="influence-primary" onClick={start} disabled={busy}><Play size={16} /> {busy ? 'Starting…' : 'Start A.5 Setup'}</button> : <p className="influence-notice">Complete the missing A.5-specific instrument configuration before starting this route.</p>}</section>}
      {test && <>
        <section className="influence-setup"><div className="section-heading"><div><span className="technical-label">A.5 SETUP</span><h2>Session conditions</h2></div><span>Derived values are read-only; actual conditions remain tester evidence.</span></div>{!test.setup ? <form onSubmit={saveSetup} className="influence-form"><label className="influence-check"><input name="environmentalConditionsStableConfirmed" type="checkbox" required /> I confirm the EUT is stabilized under constant environmental conditions for the applicable A.5 procedure.</label><label>Setup notes<textarea name="notes" rows={2} /></label><button className="influence-primary" disabled={busy}><Save size={16} /> Save setup</button></form> : <div className="influence-saved"><Check size={16} /> Setup confirmed {test.setup.notes ? `· ${test.setup.notes}` : ''}</div>}</section>
        <section className="influence-phases"><div className="section-heading"><div><span className="technical-label">TEST SEQUENCE</span><h2>Applicable A.5 procedures</h2></div><span>{phases.filter((phase: any) => phase.applicability === 'APPLICABLE').length} configured branches</span></div>{phases.map((phase: any, index: number) => <PhaseCard key={phase.code} phase={phase} index={index} active={active?.code === phase.code} snapshot={snapshot} test={test} reportId={reportId} reload={load} setError={setError} busy={busy} setBusy={setBusy} />)}</section>
        {test.status === 'COMPLETED' ? <div className="influence-next"><Check size={18} /><span>A.5 Influence Factors is complete. The final route is Endurance.</span><Link className="influence-primary" to={`/tester/reports/${reportId}/endurance`}>Continue to Endurance →</Link></div> : <button className="influence-primary influence-complete" onClick={async () => { setBusy(true); try { await axios.patch(API(reportId, '/complete')); await load(); } catch (e: any) { setError(e.response?.data?.message || 'Complete all applicable A.5 branches first.'); } finally { setBusy(false); } }} disabled={busy}>Complete Influence Factors</button>}
      </>}
      {applicability?.status !== 'NOT_APPLICABLE' && <TestProcedureInfo testId={active?.code || 'A.5.1'} configuration={{ ...snapshot, method: active?.method, powerSourceType: snapshot.powerSourceType || snapshot.powerSupplyType, applicabilityStatus: applicability?.status }} />}
    </section>
  </main>;
}

function PhaseCard({ phase, index, active, snapshot, test, reportId, reload, setError, busy, setBusy }: any) {
  const disabled = !active || phase.status === 'LOCKED';
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); setError(''); const body = Object.fromEntries(new FormData(event.currentTarget));
    try {
      if (phase.code === 'A.5.1') {
        const observations = ['LONGITUDINAL', 'TRANSVERSE'].flatMap(direction => ['NO_LOAD', 'LOW_LOAD', 'MAX_LOAD'].map(position => ({ direction, position, requiredTilt: num(body[`${direction}_${position}_requiredTilt`]), actualTilt: Number(body[`${direction}_${position}_actualTilt`]), load: Number(body[`${direction}_${position}_load`]), indication: Number(body[`${direction}_${position}_indication`]), deltaL: Number(body[`${direction}_${position}_deltaL`]), zeroError: Number(body[`${direction}_${position}_zeroError`]), unit: snapshot.unit || 'g' })));
        await axios.patch(API(reportId, '/tilting'), { zeroSettingOffConfirmed: body.zeroSettingOffConfirmed === 'on', observations });
      } else if (phase.code === 'A.5.2') {
        const observations = ['T5', 'T15', 'T30'].map(checkpoint => ({ checkpoint, observedAt: String(body[`${checkpoint}_observedAt`]), load: Number(body[`${checkpoint}_load`]), indication: Number(body[`${checkpoint}_indication`]), deltaL: Number(body[`${checkpoint}_deltaL`]), zeroError: Number(body[`${checkpoint}_zeroError`]), unit: snapshot.unit || 'g' }));
        await axios.patch(API(reportId, '/warm-up'), { disconnectedAt: body.disconnectedAt, connectedAt: body.connectedAt, stabilizationAt: body.stabilizationAt, eightHourPreconditionConfirmed: body.eightHourPreconditionConfirmed === 'on', observations });
      } else if (phase.code === 'A.5.3') {
        const targets = test.plan?.temperature?.targets || [];
        const points = targets.map((target: any) => ({ pointId: target.id, targetTemperature: target.value, actualTemperature: Number(body[`${target.id}_actual`]), stabilizedAt: new Date().toISOString(), twoHourStabilityConfirmed: body[`${target.id}_stable`] === 'on', heatingCoolingRate: Number(body[`${target.id}_rate`]), relativeHumidity: num(body[`${target.id}_rh`]), pressure: num(body[`${target.id}_pressure`]), load: Number(body[`${target.id}_load`]), indication: Number(body[`${target.id}_indication`]), deltaL: Number(body[`${target.id}_deltaL`]), zeroError: Number(body[`${target.id}_zeroError`]), unit: snapshot.unit || 'g' }));
        await axios.patch(API(reportId, '/temperature'), { points });
      } else if (phase.code === 'A.5.4') {
        const limits = test.plan?.voltage; const observations = [ ['LOWER', limits?.lower], ['UPPER', limits?.upper] ].map(([label, targetVoltage]) => ({ label, targetVoltage, actualVoltage: Number(body[`${label}_actual`]), load: Number(body[`${label}_load`]), functionBehavior: body[`${label}_behavior`] || 'OPERATED', indication: num(body[`${label}_indication`]), deltaL: num(body[`${label}_deltaL`]), zeroError: num(body[`${label}_zeroError`]), unit: snapshot.unit || 'g' }));
        await axios.patch(API(reportId, '/voltage'), { observations });
      }
      await reload();
    } catch (e: any) { setError(e.response?.data?.message || `Unable to save ${phase.code}.`); } finally { setBusy(false); }
  };
  if (phase.applicability === 'NOT_APPLICABLE') return <article className="influence-phase not-applicable"><div className="phase-index">{index + 1}</div><div><h3>{phase.code} · {phase.name}</h3><p>{phase.reason}</p></div><span>NOT APPLICABLE</span></article>;
  return <article className={`influence-phase ${active ? 'active' : ''} ${phase.status === 'COMPLETED' ? 'completed' : ''}`}><div className="phase-index">{phase.status === 'COMPLETED' ? <Check size={17} /> : disabled ? <Lock size={15} /> : index + 1}</div><div className="phase-body"><div className="phase-title"><div><h3>{phase.code} · {phase.name}</h3><p>{phase.reason}</p></div><span>{phase.status.replace(/_/g, ' ')}</span></div>{phase.status === 'COMPLETED' ? <div className="influence-saved"><Check size={15} /> Recorded result: {phase.result}</div> : active && <form onSubmit={submit} className="influence-form">{phase.code === 'A.5.1' && <TiltingForm snapshot={snapshot} />}{phase.code === 'A.5.2' && <WarmupForm />}{phase.code === 'A.5.3' && <TemperatureForm plan={test.plan?.temperature} />}{phase.code === 'A.5.4' && <VoltageForm plan={test.plan?.voltage} />}<button className="influence-primary" disabled={busy}><Save size={15} /> Save observations</button></form>}</div></article>;
}

function TiltingForm({ snapshot }: any) { return <><label className="influence-check"><input name="zeroSettingOffConfirmed" type="checkbox" required /> Automatic zero-setting / zero-tracking is OFF for this test.</label><p className="form-note">Required tilt: {snapshot.manufacturerTiltLimit ? `${snapshot.manufacturerTiltLimit}° manufacturer limit` : '50/1000 ratio where applicable'} · enter the actual achieved tilt and observations for both directions.</p>{['LONGITUDINAL', 'TRANSVERSE'].flatMap(direction => ['NO_LOAD', 'LOW_LOAD', 'MAX_LOAD'].map(position => <div className="observation-row" key={`${direction}_${position}`}><strong>{direction} · {position.replace('_', ' ')}</strong><input name={`${direction}_${position}_requiredTilt`} type="number" step="any" min="0" placeholder="Required tilt (optional)" /><input name={`${direction}_${position}_actualTilt`} type="number" step="any" min="0" placeholder="Actual tilt" required /><input name={`${direction}_${position}_load`} type="number" step="any" placeholder="Load" required /><input name={`${direction}_${position}_indication`} type="number" step="any" placeholder="Indication" required /><input name={`${direction}_${position}_deltaL`} type="number" step="any" placeholder="ΔL" required /><input name={`${direction}_${position}_zeroError`} type="number" step="any" placeholder="E₀" required /></div>))}</>; }
function WarmupForm() { return <><label>Disconnected at<input name="disconnectedAt" type="datetime-local" required /></label><label>Connected at<input name="connectedAt" type="datetime-local" required /></label><label>Indication stabilized at<input name="stabilizationAt" type="datetime-local" required /></label><label className="influence-check"><input name="eightHourPreconditionConfirmed" type="checkbox" required /> Confirm disconnected for at least 8 hours.</label>{['T5', 'T15', 'T30'].map(point => <div className="observation-row" key={point}><strong>{point}</strong><input name={`${point}_observedAt`} type="datetime-local" required /><input name={`${point}_load`} type="number" step="any" placeholder="Load" required /><input name={`${point}_indication`} type="number" step="any" placeholder="Indication" required /><input name={`${point}_deltaL`} type="number" step="any" placeholder="ΔL" required /><input name={`${point}_zeroError`} type="number" step="any" placeholder="E₀" required /></div>)}</>; }
function TemperatureForm({ plan }: any) { return <>{(plan?.targets || []).map((target: any) => <div className="observation-row" key={target.id}><strong>{target.label} · {target.value} °C</strong><input name={`${target.id}_actual`} type="number" step="any" placeholder="Actual °C" required /><input name={`${target.id}_rate`} type="number" step="any" placeholder="Rate °C/min" required /><input name={`${target.id}_rh`} type="number" step="any" placeholder="RH %" /><input name={`${target.id}_load`} type="number" step="any" placeholder="Load" required /><input name={`${target.id}_indication`} type="number" step="any" placeholder="Indication" required /><input name={`${target.id}_deltaL`} type="number" step="any" placeholder="ΔL" required /><input name={`${target.id}_zeroError`} type="number" step="any" placeholder="E₀" required /><label className="inline-check"><input name={`${target.id}_stable`} type="checkbox" required /> 2 h stable</label></div>)}</>; }
function VoltageForm({ plan }: any) { return <>{[['LOWER', plan?.lower], ['UPPER', plan?.upper]].map(([label, voltage]) => <div className="observation-row" key={String(label)}><strong>{String(label)} · target {String(voltage ?? '—')} V</strong><input name={`${label}_actual`} type="number" step="any" placeholder="Actual V" required /><input name={`${label}_load`} type="number" step="any" placeholder="Load" required /><select name={`${label}_behavior`} defaultValue="OPERATED"><option value="OPERATED">Operated as designed</option><option value="SWITCHED_OFF">Indication switched off</option></select><input name={`${label}_indication`} type="number" step="any" placeholder="Indication" /><input name={`${label}_deltaL`} type="number" step="any" placeholder="ΔL" /><input name={`${label}_zeroError`} type="number" step="any" placeholder="E₀" /></div>)}</>; }
