import { Schema, model } from 'mongoose';

const evidenceSchema = new Schema({
  reportId: { type: Schema.Types.ObjectId, ref: 'TestReport', required: true, index: true },
  mobileSessionId: { type: Schema.Types.ObjectId, ref: 'MobileEvidenceSession', index: true },
  verificationSessionId: { type: Schema.Types.ObjectId, ref: 'VerificationSession', index: true },
  checklistItemId: { type: String },
  testId: { type: String, index: true },
  subtestId: { type: String },
  instrumentId: { type: Schema.Types.ObjectId, ref: 'Instrument', index: true },
  uploaderUserId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  uploadedBy: { type: Schema.Types.ObjectId, ref: 'User', index: true },
  uploaderNameSnapshot: { type: String, required: true },
  originalFilename: { type: String, required: true },
  mimeType: { type: String, required: true, enum: ['image/jpeg', 'image/png', 'image/webp'] },
  size: { type: Number, required: true, max: 5 * 1024 * 1024 },
  fileSize: { type: Number },
  filePath: { type: String },
  storageReference: { type: String, required: true },
  sha256: { type: String, required: true },
  capturedAt: { type: Date },
  uploadedAt: { type: Date },
  captureMethod: { type: String, enum: ['MOBILE_QR', 'DESKTOP_UPLOAD'], default: 'DESKTOP_UPLOAD', index: true },
  category: { type: String, default: 'OTHER', index: true },
  evidenceType: { type: String, default: 'photo', index: true },
  title: { type: String, default: '' },
  label: { type: String, default: '' },
  description: { type: String, default: '' },
  notes: { type: String, default: '' },
  tags: { type: [String], default: [] },
  oimlReference: { type: String, default: '' },
  status: { type: String, enum: ['ACTIVE', 'ARCHIVED', 'DELETED'], default: 'ACTIVE', index: true },
  source: { type: String, enum: ['tester'], default: 'tester' },
  data: { type: Buffer, select: false },
}, { timestamps: true, collection: 'evidence' });

export const Evidence = model('Evidence', evidenceSchema);
