import { Schema, model } from 'mongoose';

const instrumentSchema = new Schema({
  registeredBy: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  manufacturer: { type: String, required: true, trim: true },
  typeDesignation: { type: String, required: true, trim: true },
  serialNumber: { type: String, required: true, trim: true, unique: true, index: true },
  accuracyClass: { type: String, enum: ['Class I', 'Class II', 'Class III', 'Class IIII'], required: true },
  indicationType: { type: String, enum: ['Self-indicating', 'Semi-self-indicating', 'Non-self-indicating'], required: true },
  zeroSettingMethod: { type: String, enum: ['Non-automatic', 'Semi-automatic', 'Automatic'] },
  zeroTracking: { type: Boolean },
  zeroIndicatingDevice: { type: Boolean },
  digitalIndication: { type: Boolean },
  indicationDamping: { type: String, enum: ['NOT_SPECIFIED', 'DAMPED', 'NON_DAMPED'] },
  unit: { type: String, enum: ['mg', 'g', 'kg', 't'], default: 'g' },
  min: { type: Number, required: true, min: 0 },
  max: { type: Number, required: true, min: 0 },
  e: { type: Number, required: true, min: 0 },
  d: { type: Number, required: true, min: 0 },
  n: { type: Number, required: true, min: 1 },
  softwareVersion: { type: String, default: '' },
  loadCellInformation: { type: String, default: '' },
  interfaces: { type: String, default: '' },
  additionalInformation: { type: String, default: '' },
  rangeType: { type: String, enum: ['single-range', 'multiple-range'], required: true },
  intervalType: { type: String, enum: ['single-interval', 'multi-interval'], required: true },
  tareDevice: { type: String, enum: ['Yes', 'No'], required: true },
  tareDevicePresent: { type: Boolean },
  tareType: { type: String, enum: ['SUBTRACTIVE', 'ADDITIVE'] },
  maximumTareEffect: { value: Number, unit: { type: String, enum: ['mg', 'g', 'kg', 't'] } },
  tareOperationMode: { type: String, enum: ['NON_AUTOMATIC', 'SEMI_AUTOMATIC', 'AUTOMATIC'] },
  tareWeighingDevicePresent: { type: Boolean },
  presetTareDevicePresent: { type: Boolean },
  multipleIndicatingDevices: { type: Boolean, required: true },
  loadReceptorType: { type: String, enum: ['normal platform', 'other / special configuration'], required: true },
  numberOfSupportPoints: { type: Number, min: 0 },
  usesElectricPower: { type: Boolean, required: true },
  powerSupplyType: { type: String, enum: ['AC mains', 'DC / battery', 'Other', 'Not specified'], required: true },
  mobileInstrument: { type: Boolean, required: true },
  portableRoadVehicleInstrument: { type: Boolean, required: true },
  rollingLoad: { type: Boolean },
  stableEquilibriumFunction: { type: Boolean },
  printingCapability: { type: Boolean },
  dataStorageCapability: { type: Boolean },
  zeroSettingCapability: { type: Boolean },
  tareCapability: { type: Boolean },
  differentiatedScaleDivisions: { type: Boolean },
  // Annex A.5 configuration is optional at registration time.  Missing
  // manufacturer/configuration data is surfaced by the applicability engine.
  hasLevelIndicator: { type: Boolean },
  hasAutomaticTiltSensor: { type: Boolean },
  manufacturerTiltLimit: { type: Number, min: 0 },
  tiltConfiguration: { type: Boolean },
  mobileOutdoorUse: { type: Boolean },
  powerSourceType: { type: String, enum: ['AC_MAINS', 'EXTERNAL_AC_DC', 'NON_RECHARGEABLE_BATTERY', 'ROAD_VEHICLE_BATTERY_12V', 'ROAD_VEHICLE_BATTERY_24V'] },
  nominalVoltage: { type: Number, min: 0 },
  minimumOperatingVoltage: { type: Number, min: 0 },
  maximumVoltage: { type: Number, min: 0 },
  specifiedVoltageRange: { min: { type: Number, min: 0 }, max: { type: Number, min: 0 } },
  threePhaseSupply: { type: Boolean },
  rechargeableBattery: { type: Boolean },
  rechargeableBatteryCanChargeDuringOperation: { type: Boolean },
  specifiedMinimumTemperature: { type: Number },
  specifiedMaximumTemperature: { type: Number },
  manufacturerReferenceTemperature: { type: Number },
}, { timestamps: true, collection: 'instruments' });

export const Instrument = model('Instrument', instrumentSchema);
