import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, FileText, Plus, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import './verification.css';

const readOnlyStatuses = new Set(['AWAITING_REVIEW', 'UNDER_REVIEW', 'COMPLETED', 'REJECTED', 'CANCELLED']);

function workflowLabel(status: unknown) { return String(status || 'NOT_TESTED').replace(/_/g, ' '); }
function resultLabel(result: unknown) { return result === 'PASS' || result === 'FAIL' || result === 'INCOMPLETE' ? String(result) : 'Not determined'; }
function routeFor(report: any) { if (report.status === 'RETEST_REQUIRED' && report.retestRequest?.testCode) return retestRoute(report.testReportId, report.retestRequest.testCode); if (readOnlyStatuses.has(String(report.status))) return `/tester/reports/${report.testReportId}/review`; if (report.status === 'TESTING') return `/tester/reports/${report.testReportId}/testing`; return `/tester/reports/${report.testReportId}`; }
function retestRoute(reportId: string, code: string) { const routes: Record<string, string> = { 'A.4.2': 'a4-2', 'A.4.3': 'a4-3', 'A.4.4': 'a4-4', 'A.4.5': 'a4-5', 'A.4.6': 'a4-6', 'A.4.7': 'a4-7', 'A.4.8': 'a4-8', 'A.4.9': 'a4-9', 'A.4.10': 'a4-10', 'A.4.11': 'a4-11', 'A.4.12': 'a4-12' }; if (code === 'A.5') return `/tester/reports/${reportId}/influence-factors`; if (code === 'A.6') return `/tester/reports/${reportId}/endurance`; return `/tester/reports/${reportId}/testing/${routes[code] || ''}`; }

export default function TesterReports() {
  const [reports, setReports] = useState<any[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const nav = useNavigate();
  useEffect(() => { void axios.get('/test-reports').then(response => setReports(response.data.reports || [])).catch(e => setError(e.response?.data?.message || 'Unable to load test reports.')); }, []);
  const filtered = useMemo(() => reports.filter(report => `${report.testReportId} ${report.instrument?.typeDesignation || ''} ${report.instrument?.serialNumber || ''} ${report.manufacturer?.name || ''}`.toLowerCase().includes(query.toLowerCase())), [reports, query]);
  return <main className="reports-page"><section className="reports-content"><header className="reports-heading"><div><span className="technical-label">TESTER WORKSPACE</span><h1>Test Reports</h1><p>One compact repository for report status, results, and history.</p></div><button className="report-primary" onClick={() => nav('/tester/new-report')}><Plus size={17} /> New Test Report</button></header>{error && <div className="report-error" role="alert">{error}</div>}<div className="report-repository-toolbar"><label className="report-search"><Search size={17} /><input aria-label="Search reports" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search report, model, serial or manufacturer" /></label><span>{filtered.length} report{filtered.length === 1 ? '' : 's'}</span></div>{filtered.length ? <section className="report-repository-list" aria-label="Test report repository">{filtered.map(report => <article className="report-repository-card" key={report.testReportId}><div className="report-repository-main"><span className="technical-label">REPORT</span><h2>{report.testReportId}</h2><p>{report.instrument?.typeDesignation || 'Instrument not recorded'} · {report.instrument?.serialNumber || 'Serial not recorded'}</p><small>{report.manufacturer?.name || report.applicant?.name || 'Manufacturer not recorded'} · {report.testerNameSnapshot || 'Tester not recorded'} · {new Date(report.updatedAt || report.createdAt).toLocaleDateString()}</small></div><div className="report-repository-state"><span className="report-status">{workflowLabel(report.status)}</span><strong>{resultLabel(report.result)}</strong><small>{report.stage || 'APPLICATION'}</small></div><button className="report-inline-action report-open-action" type="button" onClick={() => nav(routeFor(report))}>{report.status === 'RETEST_REQUIRED' ? 'Review Retest' : 'View Report'} <ArrowRight size={15} /></button></article>)}</section> : <section className="reports-empty"><FileText size={26} /><h2>{query ? 'No matching reports' : 'No test reports yet'}</h2><p>{query ? 'Try a different report, model, serial, or manufacturer.' : 'Start a new test report to create the first application record.'}</p>{!query && <button className="report-primary" onClick={() => nav('/tester/new-report')}><Plus size={16} /> New Test Report</button>}</section>}</section></main>;
}
