import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Check, LogOut, Save } from 'lucide-react';
import axios from 'axios';
import { Link, useNavigate, useParams } from 'react-router-dom';
import './styles/report-edit.css';

type Form = { applicationNumber: string; referenceMode: 'generated' | 'external'; externalApplicationReference: string; organization: string; contactName: string; email: string; phone: string; address: string };
const empty: Form = { applicationNumber: '', referenceMode: 'generated', externalApplicationReference: '', organization: '', contactName: '', email: '', phone: '', address: '' };
const phoneDigits = (value: string) => value.replace(/^\+91\s?/, '').replace(/\D/g, '');

export default function ReportApplicationEdit() {
  const { reportId = '' } = useParams(); const nav = useNavigate(); const [report, setReport] = useState<any>(); const [form, setForm] = useState<Form>(empty); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void axios.get(`/test-reports/${reportId}`).then(response => { const value = response.data.report; setReport(value); setForm({ applicationNumber: value.applicationNumber || '', referenceMode: value.externalApplicationReference ? 'external' : 'generated', externalApplicationReference: value.externalApplicationReference || '', organization: value.applicant?.name || value.manufacturer?.name || '', contactName: value.applicant?.contactName || '', email: value.applicant?.email || '', phone: phoneDigits(value.applicant?.contactNumber || ''), address: value.applicant?.address || '' }); }).catch(e => setError(e.response?.data?.message || 'Unable to load report.')); }, [reportId]);
  const set = (key: keyof Form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const invalid = !form.applicationNumber.trim() || !form.organization.trim() || !form.contactName.trim() || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(form.email) || !/^\d{10}$/.test(form.phone) || !form.address.trim() || (form.referenceMode === 'external' && !form.externalApplicationReference.trim());
  const save = async (event: FormEvent) => { event.preventDefault(); if (invalid) return setError('Complete the required fields. Check the email, external reference, and 10-digit Indian phone number.'); setBusy(true); setError(''); try { await axios.patch(`/test-reports/${reportId}/application`, { applicationNumber: form.applicationNumber, referenceMode: form.referenceMode, externalApplicationReference: form.externalApplicationReference, applicant: { name: form.organization, contactName: form.contactName, email: form.email, contactNumber: `+91 ${form.phone}`, address: form.address } }); nav(`/tester/reports/${reportId}`); } catch (e: any) { setError(e.response?.data?.message || 'Unable to save application details.'); } finally { setBusy(false); } };
  if (!report) return <main className="report-edit-page"><div className="verification-loading">{error || 'Loading report…'}</div></main>;
  return <main className="report-edit-page"><header className="workspace-top"><Link to={`/tester/reports/${reportId}`}><ArrowLeft size={16} /> Report</Link><div className="workspace-brand"><strong>NAWI</strong><span>TEST &amp; REPORT SYSTEM</span></div><button className="report-logout" onClick={() => { axios.post('/auth/logout').finally(() => nav('/login')); }}><LogOut size={15} /> Sign out</button></header><section className="report-edit-content"><div className="workspace-heading"><div><span className="technical-label">REPORT METADATA</span><h1>Edit Report</h1><p>Update application and applicant details for {report.testReportId}.</p></div><span className="workspace-status active">Editable</span></div><form className="report-edit-card" onSubmit={save}><div className="report-edit-card-heading"><span className="technical-label">APPLICATION &amp; APPLICANT</span><h2>Report contact record</h2><p>These fields use the same validation as New Test Report.</p></div><div className="report-edit-grid"><label>Reference mode<select value={form.referenceMode} onChange={e => set('referenceMode', e.target.value)}><option value="generated">Generated application number</option><option value="external">External reference</option></select></label><label>Application number<input value={form.applicationNumber} onChange={e => set('applicationNumber', e.target.value)} required /></label><label className="wide">External application reference<input value={form.externalApplicationReference} onChange={e => set('externalApplicationReference', e.target.value)} disabled={form.referenceMode !== 'external'} /></label><label>Applicant / manufacturer<input value={form.organization} onChange={e => set('organization', e.target.value)} required /></label><label>Contact person<input value={form.contactName} onChange={e => set('contactName', e.target.value)} required /></label><label>Email<input type="email" value={form.email} onChange={e => set('email', e.target.value)} required /></label><label>Phone<input inputMode="numeric" value={form.phone} onChange={e => set('phone', e.target.value.replace(/\D/g, '').slice(0, 10))} required /></label><label className="wide">Address<textarea value={form.address} onChange={e => set('address', e.target.value)} required rows={3} /></label></div>{error && <div className="report-error">{error}</div>}<div className="report-edit-actions"><Link className="report-secondary" to={`/tester/reports/${reportId}`}>Cancel</Link><button className="report-primary" disabled={busy || invalid}>{busy ? 'Saving…' : 'Save Changes'}{busy ? <Save size={16} /> : <Check size={16} />}</button></div></form></section></main>;
}
