import React, { useState } from 'react';
import { ChevronRight, Eye, EyeOff, Lock, Mail } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { useAuth } from '../../app/providers/AuthProvider';
import AmbientShapes from '../../shared/components/ambient/AmbientShapes';
import Logo from '../../shared/components/Logo';
import './login.css';

function Field({ label, value, onChange, placeholder, icon }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; icon?: React.ReactNode }) {
  return <label className="field"><span>{label}</span><div className="input-wrap">{icon}<input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} /></div></label>;
}
function Password({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) {
  const [show, setShow] = useState(false);
  return <label className="field"><span>{label}</span><div className="input-wrap"><Lock /><input type={show ? 'text' : 'password'} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} /><button type="button" aria-label="Show or hide password" onClick={() => setShow(!show)}>{show ? <EyeOff /> : <Eye />}</button></div></label>;
}
function AuthLayout({ children, title, subtitle, scroll = false }: { children: React.ReactNode; title: string; subtitle: string; scroll?: boolean }) {
  const [offset, setOffset] = useState({ x: 0, y: 0 });
  const moveCard = (event: React.MouseEvent<HTMLElement>) => {
    if (window.innerWidth <= 760) return;
    const bounds = event.currentTarget.getBoundingClientRect();
    const x = (event.clientX - (bounds.left + bounds.width / 2)) / bounds.width;
    const y = (event.clientY - (bounds.top + bounds.height / 2)) / bounds.height;
    setOffset({ x: Number((x * 3.5).toFixed(2)), y: Number((y * 2.5).toFixed(2)) });
  };
  const style = { '--card-x': `${offset.x}px`, '--card-y': `${offset.y}px`, '--card-rx': `${(offset.x / 3.5 * 0.35).toFixed(3)}deg`, '--card-ry': `${(-offset.y / 2.5 * 0.25).toFixed(3)}deg` } as React.CSSProperties;
  return <main className={`page ${scroll ? 'auth-scroll' : ''}`} onMouseMove={moveCard} onMouseLeave={() => setOffset({ x: 0, y: 0 })}><AmbientShapes variant="login" /><header className="site-header"><Link className="auth-logo-link" to="/login"><Logo dark animated /></Link><span className="pill">OIML R-76</span><span className="header-product">Test &amp; Report System</span></header><section className="auth-card" style={style}><section className="hero-panel"><p className="eyebrow">NAWI TEST &amp; REPORT SYSTEM</p><h2>Precision in<br />every<br /><em>measurement.</em></h2><p className="hero-copy">Build, manage and review test records with confidence. A modern platform for OIML R-76 compliance.</p><div className="feature-row"><span>Trusted<br />Records</span><span>Transparent<br />Process</span><span>Global<br />Standards</span></div><div className="hero-foot">OIML R-76 • Legal Metrology • Digital Workflow</div></section><section className="form-panel"><div className="form-content"><div className="blue-rule" /><h1>{title}</h1><p className="sub">{subtitle}</p>{children}</div></section></section><footer>© 2026 NAWI | Legal Metrology | Digital Workflow</footer></main>;
}
export function LoginPage() {
  const { login } = useAuth(); const nav = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <AuthLayout title="Welcome back" subtitle="Sign in to your NAWI workspace"><form onSubmit={async event => { event.preventDefault(); setBusy(true); try { const response = await axios.post('/auth/login', { email, password }); login(response.data.user); nav('/'); } catch (error: any) { setError(error.response?.data?.message || 'Unable to sign in.'); } finally { setBusy(false); } }}><Field label="Email address" value={email} onChange={setEmail} placeholder="you@organisation.gov" icon={<Mail />} /><Password label="Password" value={password} onChange={setPassword} placeholder="Enter your password" />{error && <div className="error">{error}</div>}<div className="row"><Link to="/forgot-password">Forgot password?</Link></div><button className="primary" disabled={busy} aria-busy={busy}>{busy ? 'Signing in…' : 'Sign in'}<ChevronRight /></button><p className="switch">New to the system? <Link to="/signup">Create an account</Link></p></form></AuthLayout>;
}
export function SignupPage() {
  const { login } = useAuth(); const nav = useNavigate(); const [values, setValues] = useState({ firstName: '', lastName: '', email: '', password: '', confirm: '' }); const [terms, setTerms] = useState(false); const [error, setError] = useState(''); const set = (key: keyof typeof values, value: string) => setValues(current => ({ ...current, [key]: value }));
  return <AuthLayout scroll title="Create your account" subtitle="Set up your account to begin working with NAWI test records and reports"><form onSubmit={async event => { event.preventDefault(); if (values.password !== values.confirm) return setError('Passwords do not match.'); if (!terms) return setError('Please accept the Terms and Conditions.'); try { const response = await axios.post('/auth/register', { ...values, terms }); login(response.data.user); nav('/'); } catch (error: any) { setError(error.response?.data?.message || 'Unable to create account.'); } }}><div className="twocol"><Field label="First name" value={values.firstName} onChange={value => set('firstName', value)} /><Field label="Last name" value={values.lastName} onChange={value => set('lastName', value)} /></div><Field label="Email address" value={values.email} onChange={value => set('email', value)} placeholder="you@organisation.gov" icon={<Mail />} /><Password label="Password" value={values.password} onChange={value => set('password', value)} placeholder="Create a password" /><Password label="Confirm password" value={values.confirm} onChange={value => set('confirm', value)} placeholder="Repeat your password" /><small className="hint">Use at least 8 characters with a mix of letters and numbers.</small><label className="check"><input type="checkbox" checked={terms} onChange={event => setTerms(event.target.checked)} /> I agree to the Terms and Conditions</label>{error && <div className="error">{error}</div>}<button className="primary">Create account<ChevronRight /></button><p className="switch">Already have an account? <Link to="/login">Sign in</Link></p></form></AuthLayout>;
}
export function SimpleAuthPage() { const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); return <AuthLayout scroll title="Recover your account" subtitle="We’ll help you get back into your NAWI workspace"><form onSubmit={async event => { event.preventDefault(); const response = await axios.post('/auth/forgot-password', { email }); setMessage(response.data?.message || 'Request completed.'); }}><Field label="Email address" value={email} onChange={setEmail} placeholder="you@organisation.gov" icon={<Mail />} />{message && <div className="success">{message}</div>}<button className="primary">Send reset instructions<ChevronRight /></button><p className="switch"><Link to="/login">Back to sign in</Link></p></form></AuthLayout>; }
